_load._new('scr/links.js')
var links=[];
function adl(t,l){ var ll=links.length-1; ll++;links[ll]={title:t,href:l} }
{//adl('Bible-BG web links'                         ,'../scr/links.htm')
// adl('Bible-BG'                                   ,'http://bible-bg.hit.bg/')
   adl('Двери БГ.Библия'                            ,'http://dveribg.net/bible')
   adl('Двери БГ.Търсене в Библията'                ,'http://www.dveri.bg/content/view/286/173/')
   adl('Православното християнство'                 ,'http://www.pravoslavnoto-hristianstvo.com/')
   adl('библия'                                     ,'http://www.pravoslavnoto-hristianstvo.com/heritage/bible/')
   adl('pravoslavieto.com'                          ,'http://www.pravoslavieto.com/bible/nastavlenija_po_temi.htm')
   adl('Св. Писание в Интернет'                     ,'http://www.pravoslavieto.com/bible/bibles_online.htm')
   adl('БИБЛЕЙСКИ КНИГИ'                            ,'http://www.trinity-bg.org/b&dic/dic/contents.html')
   adl('CrossBgBible'                               ,'http://sourceforge.net/projects/crossbgbible/')
   adl('CrossBgBible'                               ,'http://www.bibliata.com/')
   adl('Библии Он-Лайн в России'                    ,'http://www.bible.ru')
   adl('The SWORD project'                          ,'http://www.crosswire.org' )
   adl('Компютърна Библия.Ваньо Георгиев'           ,'http://www.vanyog.com/bible')
   adl('bgbible.com'                                ,'http://www.bgbible.com/riggs/contents.htm')
   adl('synpress.bglink.net'                        ,'http://synpress.bglink.net/index_bible.htm')
   adl('Православното християнство'                 ,'http://bg.orthodoxwiki.org/index.php')
   adl('Daxy.com'                                   ,'http://www.daxy.com/cgi-bin/page.py?ind=freebibl')
   adl('сайт за глухи/глухонеми хора'               ,'http://123.dir.bg/')
   adl('biblia.duh-i-istina.net'                    ,'http://biblia.duh-i-istina.net/index.php')
   adl('Библия на църковнославянски език'           ,'http://www.wco.ru/biblio/books/bible_cs/main.htm')
   adl('Библия на славянском языке'                 ,'http://www.pues.ru/orthodox/bible.htm')
   adl('Священное писание'                          ,'http://www.kuraev.ru/forum/bible.php?book_id=&glava=&group_id=')
   adl('Священное писание'                          ,'http://www.orthodox.spb.ru/bible/Index.htm')
   adl('Священное писание'                          ,'http://212.188.13.168/izdat/')
   adl('Программа'                                  ,'http://www.ipmce.su/%7Eigor/bible.html')
   adl('Программа'                                  ,'http://come.to/sbible')
   adl('Поиск-Search-Kerese\'s'                     ,'http://orthodoxia.org/rus/bible')
   adl('King James Version (KJV)'                   ,'http://www.biblegateway.com/cgi-bin/bible?version=KJV&passage=all&language=english')
   adl('The Septuagint'                             ,'http://students.cua.edu/16kalvesmaki/lxx/')
   adl('Bibelen pa norsk'                           ,'http://www.gospelcom.net/bible?language=Norsk')
   adl('audio-bible.com'                            ,'http://www.http://www.audio-bible.com//')
   adl('The CrossWire Bible Society'                ,'http://www.crosswire.org/index.jsp')
   adl('Orthodox'                                   ,'http://junecalends.50free.net/')                                                     
// --- from CrossBbBible
   adl('Български Християнски WEB портал'           ,'http://bibliata.com/'  )
   adl('Български Християнски TV портал'            ,'http://bibliata.tv/'   )
   adl('Християнски проповеди'                      ,'http://propovedi.net/' )
   adl('Християнска музика'                         ,'http://hvalenie.com/'  )
   adl('Молитва за България'                        ,'http://molitvata.com/' )
   adl('Библейска святост'                          ,'http://osveten.com/'   )
   adl('Български християнски емейл'                ,'http://spasen.com/'    )
   adl('Библейско лидерство'                        ,'http://lidersko.info/' )
   adl('Християнски новини'                         ,'http://www.evangelsko.info/')
   adl('Християнски просветен център'               ,'http://www.prosveten.com/'  )
   adl('Библейско богословие'                       ,'http://www.bogoslovie.com/' )
   adl('Институт за българска протестантска история','http://www.protestantstvo.com/')
   adl('Капеланство - Бг'                           ,'http://www.kapelanstvo.com/'   )
   adl('Български православен каталог'              ,'http://www.pravoslavieto.com/' )
   adl('Български Християнски уебпортал'            ,'http://hristianstvo.start.bg/' )
   adl('Евангелски вестник'                         ,'http://www.evangelskivestnik.net/' )
   adl('Списание "Божия Любов"'                     ,'http://bozhialiubov.christian.net/')
   adl('Списание "Братска Любов"'                   ,'http://www.bratskalubov.hit.bg/'   )
   adl('Жития на светиите'                          ,'http://www.pravoslavieto.com/2/prez_vekovete/zhitija.htm')
}
_load._end()
