load_new('scr/js-export.js')
function JsExport(pto,catalog,fext,Win_Mac,date){
    HDRclr='black';  HDRfon='gray';
    SETclr='yellow'; SETfon='black';
    TXTclr='white';  TXTfon='#666699';/*lila*/
    TXTclr='black';
var k,TestStr,savebuf,mes, TestSz, DefSz
                        // TestSz:string[3]; DefSz:string[3]
  outf=pto+catalog+fext
  log('=== JS export:'+outf+eol+br);
  /*--- open ---*/
    iomode=2 // iomode=1:read, 2:write 8:append
    createNewIfUnexist=true
    // =True:Unicode                
    // =False:ascii  - if omitted, the file is opened as ASCII. 
    // =TristateUseDefault?:system default  
    Unicode=false 
    save=fso.OpenTextFile(outf,iomode,createNewIfUnexist,Unicode);
    
    //  overwrite=true/false (if omitted)
    //  save=fso.CreateTextFile(,overwrite ,unicode);
  /*---*/                              
  save.write("log('>>>"+catalog+".js');") 
  save.write('Fnt=['); var v=',',s=' ',no;
  save.write('// #[Type,Style, PathNo,SetNo,Win,PS,File,Flag,Bad, RWin,RPs,RStWin,RStPs]'+eol);
  for (k=0; k<=LastFont; k++) with (Fonts[k]){
    if(k>0) s=v; 
	no='/*'+k+'*/' // fc(k,4,' ')+GetFontErr(k)
	save.write(no+s+'["'+TypeCh +'","'+StyleCh +'"'+ ','  +PathNo  +','  +SetNo  
	          + ',"' +WinName +'","'+PSname +'","'+FileName+'"'+',"' +Flag    +'",' +Bad       
			  + ','  +RepWin  +','  +RepPs  +',"' +RepStWin+'","'+RepStPs+'"' +']'+eol)
  }; save.write(']'+eol)

  save.write('Set=['); var v=',',s=' ',no;
  save.write('// #[TT,PS,Set]'+eol);
  for (k=0; k<=LastSet; k++)  with (Sets[k]) {
    if(k>0) s=v; 
	no='/*'+k+'*/'
    save.write(no+s+'['+TTfil+','+PSfil+','+ '"'+Name+'"'+']'+eol)
  }; save.write(']'+eol)
  
  save.write('Pth=['); var v=',',s=' ',no;
  save.write('// #[files,Path]'+eol);
  for (k=0; k<=LastPath; k++) with (Paths[k]){
    if(k>0) s=v; 
	no='/*'+k+'*/'
	save.write(no+s+'['+Pfiles+','+'"'+Name+'"'+']'+eol)
  }; save.write(']'+eol)
  save.write('Win_Mac="'+Win_Mac+'"; catalog="'+catalog+'";'+eol
  +"loadstatus='data loaded';log('<<<');"+'a2def();'+eol)
  save.write("// "+gener+eol);
  save.Close();// Close(Out_fh);
  log('=== JS exported.'+eol+br);
}// ------------------------------------------------

/**-/ // --- fontorg-catalog.htm ---
<HTML><HEAD>
  <meta http-equiv="Content-Type" content="text/html; charset=Windows-1251">
  <TITLE>Fontorg.3.1b.js</TITLE>
<script src="scr/fontorg-def.js"></script>
<script>
  if(typeof(loadstatus)=='undefined' || loadstatus!='.')
    document.write('<pre> --- miss/load/syntax error in file "fontorg-def.js"</pre><br>')
</script>
<script src="afs/ea-2010.js"></script>
</HEAD>
<BODY FACE=Arial" size=3 COLOR="black" BGcolor="gray" VALIGN="top">
<FONT SIZE=1><HR>Generated by Fontorg
<script>
  if(typeof(loadstatus)=='undefined' || loadstatus!='.')
    document.write('<pre> --- miss/load/syntax error in data file</pre><br>')
  else {ShowFontCatalog();}
</script>
</BODY></HTML>
/**/
load_end()