// --- file:'F:\elefter.dev\svc\svc_usr.js', made_by:'SVC-init.cmd', at:'2021.11.23 19:24:02.90' ---
comp="P55A_W7-64"
  os="win-7"
user="elefter"
 log="C:/$desk/$svc.jobs/svc.elefter.log"
zint="F:/elefter.dev/svc/zint-2.10.0/Zint.exe"
root="C:/$desk/"
jobs="C:/$desk/$svc.jobs/"
 eps="C:/$desk/$svc.jobs/eps/"
 pdf="C:/$desk/$svc.jobs/pdf/"
