// subs:69 files:1025
files_list=[
  ["n","SVC-8"]
 ,["k","fld"] ,["p","SVC-8"]
 ,["f","svc-8.npp.ses,.ses,,,,ses"]
 ,["f","svc-8.bat,.bat,,,,scr_cmd"]
 ,["f","SVC-8.hta,.hta,,,,scr_cmd"]
 ,["f","SVC-8.htm,.htm,,,,web_cont"]
 ,["f","_barcodes.js,.js,,,,web_cont"]
 ,["f","_fs.js,.js,,,,web_cont"]
 ,["f","_gui.js,.js,,,,web_cont"]
 ,["f","_pers.js,.js,,,,web_cont"]
 ,["f","jquery-3.5.1.js,.js,,,,web_cont"]
 ,["f","svc-scheme-3.svg,.svg,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","svc-8.lst,.lst,,,,txt_data"]
 ,["f","svc-8.md5,.md5,,,,txt_data"]
 ,["f","svc-8.zip,.zip,,,,bin_arch"]
 ,["f","R19G00001.ico,.ico,,,,bin_pic"]
 ,["f","$svc.usr,.usr,,,,etc"]
 ,["f","_fs-csv.js,.js,,,,etc"]
 ,["f","_global.js,.js,,,,etc"]
 ,["f","_gui_help.js,.js,,,,etc"]
 ,["f","svc-8.files.js,.js,,,,etc"]

 ,["k","work"] ,[">","C:/$desk/#pers/"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","#pers_elefter.log,.log,,,,txt_data"]

 ,["k","data"] ,[">","C:/$desk/#pers/#data"]
 ,["f","190413_1_Code-128.indd.csv,.csv,,,,txt_data"]
 ,["f","190734_1_Code-128.indd.csv,.csv,,,,txt_data"]
 ,["f","193408_1.1_Code-128.zint.csv,.csv,,,,txt_data"]
 ,["f","193408_1_Code-128.zint.csv,.csv,,,,txt_data"]
 ,["f","194890_2_Code-128.zint.csv,.csv,,,,txt_data"]
 ,["f","A19E07001.eps,.eps,,,,bin_publ"]
 ,["f","A19E07003.eps,.eps,,,,bin_publ"]
 ,["f","R19G00001.eps,.eps,,,,bin_publ"]
 ,["f","R19G00003.eps,.eps,,,,bin_publ"]
 ,["f","R19G00005.eps,.eps,,,,bin_publ"]
 ,["f","190413_1_Code-128.zint.csv,.csv,,,,etc"]
 ,["f","193408_1.1_Code-128.indd.csv,.csv,,,,etc"]
 ,["f","193408_1_Code-128.indd.csv,.csv,,,,etc"]
 ,["f","194890_2_Code-128.indd.csv,.csv,,,,etc"]
 ,["f","A19E07002.eps,.eps,,,,etc"]
 ,["f","A19E07004.eps,.eps,,,,etc"]
 ,["f","R19G00002.eps,.eps,,,,etc"]
 ,["f","R19G00004.eps,.eps,,,,etc"]
 ,["f","R19G00006.eps,.eps,,,,etc"]

 ,["n","FontOrg"]
 ,["k","fld"] ,["p","fontorg.js"]
 ,["f","fontorg srciptdev.ses,.ses,,,,ses"]
 ,["f","fontorg.npp.ses,.ses,,,,ses"]
 ,["f","fontorg-catalog.hta,.hta,,,,scr_cmd"]
 ,["f","fontorg.hta,.hta,,,,scr_cmd"]
 ,["f","fontorg-catalog.htm,.htm,,,,web_cont"]
 ,["f","fontorg3.htm,.htm,,,,web_cont"]
 ,["f","fontorg.files.js,.js,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","FontOrg.lst,.lst,,,,txt_data"]
 ,["f","FontOrg.md5,.md5,,,,txt_data"]
 ,["f","fnt.lnk,.lnk,,,,bin_ptr"]
 ,["f","fntA.ico,.ico,,,,bin_pic"]
 ,["f","fntTT.ico,.ico,,,,etc"]
 ,["f","fontorg-info.htm,.htm,,,,etc"]

 ,["k","afs"] ,["p","fonts-data"]
 ,["f","2010.11 ea.js,.js,,,,web_cont"]
 ,["f","2010.12 ea.js,.js,,,,web_cont"]
 ,["f","1998.06 plakat-APUS.AFS,.AFS,,,,etc"]
 ,["f","1998.06 plakat-PULSAR.afs,.afs,,,,etc"]
 ,["f","2002.07 dnevnik-InDesign20CE.afs,.afs,,,,etc"]
 ,["f","2003.08 dnevnik-InDesign20CE.afs,.afs,,,,etc"]
 ,["f","2003.08 windows-Starter-Set.afs,.afs,,,,etc"]
 ,["f","2004.11 dnevnik.afs,.afs,,,,etc"]
 ,["f","2006.10 bulsa.afs,.afs,,,,etc"]
 ,["f","2007.01 ea.afs,.afs,,,,etc"]
 ,["f","2007.04 praktis-a.afs,.afs,,,,etc"]
 ,["f","2007.04 praktis-b.afs,.afs,,,,etc"]
 ,["f","2008.01 praktis-a.afs,.afs,,,,etc"]
 ,["f","2008.01 praktis-b.afs,.afs,,,,etc"]
 ,["f","2008.11 majority3-b.afs,.afs,,,,etc"]
 ,["f","2008.12 ea-a.afs,.afs,,,,etc"]
 ,["f","2008.12 ea-b.afs,.afs,,,,etc"]
 ,["f","2009.03 jimi Starter Set.afs,.afs,,,,etc"]
 ,["f","2009.03 jimi nonserif.afs,.afs,,,,etc"]
 ,["f","2010.06 kamea-comp2-c.afs,.afs,,,,etc"]
 ,["f","2010.08 ea.afs,.afs,,,,etc"]
 ,["f","2010.11 ea.afs,.afs,,,,etc"]
 ,["f","2010.12 ea.afs,.afs,,,,etc"]
 ,["f","2010.12 ea.reg,.reg,,,,etc"]

 ,["k","lib"] ,["p","lib"]
 ,["f","activex-init.js,.js,,,,web_cont"]
 ,["f","env.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","paths.js,.js,,,,web_cont"]
 ,["f","subwindows.js,.js,,,,web_cont"]
 ,["f","load_err.log,.log,,,,txt_data"]
 ,["f","load.js.lnk,.lnk,,,,bin_ptr"]
 ,["f","date.js,.js,,,,etc"]
 ,["f","load.js,.js,,,,etc"]
 ,["f","out-htm2.js,.js,,,,etc"]
 ,["f","root&load.js,.js,,,,etc"]
 ,["f","utils.js,.js,,,,etc"]

 ,["k","scr"] ,["p","scr"]
 ,["f","afs-load.js,.js,,,,web_cont"]
 ,["f","fontorg-def.js,.js,,,,web_cont"]
 ,["f","fontorg-func.js,.js,,,,web_cont"]
 ,["f","fontorg-ui.js,.js,,,,web_cont"]
 ,["f","reg.js,.js,,,,web_cont"]
 ,["f","stl.js,.js,,,,web_cont"]
 ,["f","fo-.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","!fonts.ind-tags-txt.txt,.txt,,,,txt_data"]
 ,["f","fo.css,.css,,,,etc"]
 ,["f","fontorg-desc.js,.js,,,,etc"]
 ,["f","fontorg-info.js,.js,,,,etc"]
 ,["f","js-export.js,.js,,,,etc"]
 ,["f","rtf-export.js,.js,,,,etc"]
 ,["f","styles.js,.js,,,,etc"]

 ,["n","psw"]
 ,["k","fld"] ,["p","psw"]
 ,["f","psw.hta,.hta,,,,scr_cmd"]
 ,["f","psw.htm,.htm,,,,web_cont"]
 ,["f","psw2.htm,.htm,,,,web_cont"]
 ,["f","psw.js,.js,,,,web_cont"]
 ,["f","psw.css,.css,,,,web_cont"]
 ,["f","DESKTOP.INI,.ini,,,,txt_data"]
 ,["f","encript.ico,.ico,,,,bin_pic"]

 ,["k","data"] ,["p","data"]
 ,["f","lastpass-export.htm,.htm,,,,web_cont"]
 ,["f","index.html,.html,,,,web_cont"]
 ,["f","psw.elefter.js,.js,,,,web_cont"]
 ,["f","psw1.elefter.js,.js,,,,web_cont"]
 ,["f","psw2.elefter.lastpass-old.js,.js,,,,web_cont"]
 ,["f","psw3.elefter.old.js,.js,,,,web_cont"]
 ,["f","ext-all.css,.css,,,,web_cont"]
 ,["f","2010.12 ea operapass.xml,.xml,,,,txt_data"]
 ,["f","lastpass!.txt,.txt,,,,txt_data"]
 ,["f","p.txt,.txt,,,,txt_data"]
 ,["f","psw-.txt,.txt,,,,txt_data"]
 ,["f","psw.txt,.txt,,,,txt_data"]
 ,["f","2010.12 ea foxpass.csv,.csv,,,,txt_data"]
 ,["f","2010.12 ea iepass.csv,.csv,,,,txt_data"]
 ,["f","elefter lastpass.csv,.csv,,,,txt_data"]
 ,["f","lastpass 2014-09-15 ea.csv,.csv,,,,txt_data"]
 ,["f","psw.elefter.lastpass 2013-02-16.csv,.csv,,,,txt_data"]
 ,["f","psw2.elefter.lastpass-new.csv,.csv,,,,txt_data"]
 ,["f","psw data.zip,.zip,,,,bin_arch"]
 ,["f","psw2-.rar,.rar,,,,bin_arch"]
 ,["f","2010.12 ea iepass-keepass.csv,.csv,,,,etc"]
 ,["f","2010.12 ea operapass.csv,.csv,,,,etc"]
 ,["f","lastpass 2011.05.31.csv,.csv,,,,etc"]
 ,["f","lastpass-2012-02-07.csv,.csv,,,,etc"]
 ,["f","psw-.zip,.zip,,,,etc"]
 ,["f","psw2.rar,.rar,,,,etc"]
 ,["f","psw4.elefter.all.js,.js,,,,etc"]

 ,["n","proj"]
 ,["k","fld"] ,["p","proj"]
 ,["f","proj.npp.ses,.ses,,,,ses"]
 ,["f","proj.cmd,.cmd,,,,scr_cmd"]
 ,["f","proj.hta,.hta,,,,scr_cmd"]
 ,["f","proj.htm,.htm,,,,web_cont"]
 ,["f","$sys.js,.js,,,,web_cont"]
 ,["f","files_list.js,.js,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","proj.lst,.lst,,,,txt_data"]
 ,["f","proj.md5,.md5,,,,txt_data"]
 ,["f","proj.zip,.zip,,,,bin_arch"]
 ,["f","proj.js,.js,,,,etc"]

 ,["n","run-hta"]
 ,["k","fld"] ,["p","run-hta"]
 ,["f","run-hta.Sci.ses,.ses,,,,ses"]
 ,["f","run-hta.npp.ses,.ses,,,,ses"]
 ,["f","run.cmd,.cmd,,,,scr_cmd"]
 ,["f","run.hta,.hta,,,,scr_cmd"]
 ,["f","run.htm,.htm,,,,web_cont"]
 ,["f","lib.fs.js,.js,,,,web_cont"]
 ,["f","run-proj.js,.js,,,,web_cont"]
 ,["f","torfiles.js,.js,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","run-hta.lst,.lst,,,,txt_data"]
 ,["f","run-hta.md5,.md5,,,,txt_data"]
 ,["f","run-hta.zip,.zip,,,,bin_arch"]
 ,["f","run.cmd eng.hta file.'..calendar.hta' par.'1,3,1'.lnk,.lnk,,,,bin_ptr"]
 ,["f","lib.loader.js,.js,,,,etc"]

 ,["n","proj-list"]
 ,["k","fld"] ,["p","proj-list"]
 ,["f","proj-list.npp.ses,.ses,,,,ses"]
 ,["f","proj-list.hta,.hta,,,,scr_cmd"]
 ,["f","vol..scan.hta,.hta,,,,scr_cmd"]
 ,["f","proj-list.htm,.htm,,,,web_cont"]
 ,["f","vol..load.htm,.htm,,,,web_cont"]
 ,["f","boot-log..proj-list.js,.js,,,,web_cont"]
 ,["f","html.row_sds.js,.js,,,,web_cont"]
 ,["f","proj-list..dropbox.js,.js,,,,web_cont"]
 ,["f","proj-list..proj-list.js,.js,,,,web_cont"]
 ,["f","proj-list.def.js,.js,,,,web_cont"]
 ,["f","proj-list.scan_fs.js,.js,,,,web_cont"]
 ,["f","vol..all.js,.js,,,,web_cont"]
 ,["f","vol..this.js,.js,,,,web_cont"]
 ,["f","vol.d.this.js,.js,,,,web_cont"]
 ,["f","vol.f.this.js,.js,,,,web_cont"]
 ,["f","proj-list.styles.css,.css,,,,web_cont"]
 ,["f","vol..styles.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","Newdev.txt,.txt,,,,txt_data"]
 ,["f","HTTP requests -- Eloquent JavaScript.URL,.url,,,,web_ptr"]
 ,["f","javascript - JSON and XMLHttpRequest - Stack Overflow.URL,.url,,,,web_ptr"]
 ,["f","fldr_1blue.ico,.ico,,,,bin_pic"]
 ,["f","proj-list..googledisk.js,.js,,,,etc"]
 ,["f","proj-list..projects.js,.js,,,,etc"]
 ,["f","proj-list.export_project.js,.js,,,,etc"]
 ,["f","proj-list.show_files.js,.js,,,,etc"]
 ,["f","vol..def.js,.js,,,,etc"]
 ,["f","vol..scan.htm,.htm,,,,etc"]
 ,["f","vol.c.this.js,.js,,,,etc"]
 ,["f","vol.e.this.js,.js,,,,etc"]

 ,["n","proj-info"]
 ,["k","fld"] ,["p","proj-info"]
 ,["f","proj-info-.npp.ses,.ses,,,,ses"]
 ,["f","proj-info.npp.ses,.ses,,,,ses"]
 ,["f","proj-info.hta,.hta,,,,scr_cmd"]
 ,["f","lib-interfaces.js.htm,.htm,,,,web_cont"]
 ,["f","proj-info.htm,.htm,,,,web_cont"]
 ,["f","proj-info.projinfo.htm,.htm,,,,web_cont"]
 ,["f","proj-info.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","proj-info.bible-bg.txt,.txt,,,,txt_data"]
 ,["f","APPS Info.ico,.ico,,,,bin_pic"]
 ,["f","proj-info.proj,.proj,,,,etc"]

 ,["k","scr"] ,["p","scr"]
 ,["f","conditions.js,.js,,,,web_cont"]
 ,["f","proj-dump.js,.js,,,,web_cont"]
 ,["f","proj-scan.js,.js,,,,web_cont"]
 ,["f","proj-ui.js,.js,,,,web_cont"]
 ,["f","proj-info.css,.css,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","proj-tags.js,.js,,,,etc"]

 ,["n","run-cmd"]
 ,["k","fld"] ,["p","run-cmd"]
 ,["f","run-cmd.npp.ses,.ses,,,,ses"]
 ,["f","PowerOff.cmd,.cmd,,,,scr_cmd"]
 ,["f","conditional shutdown.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-apl.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-dbg.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-off.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-on.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-sys.cmd,.cmd,,,,scr_cmd"]
 ,["f","run-cmd.files.js,.js,,,,web_cont"]
 ,["f","netscan portable.xml,.xml,,,,txt_data"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","run.lst,.lst,,,,txt_data"]
 ,["f","run.md5,.md5,,,,txt_data"]
 ,["f","netscan portable.exe,.exe,,,,bin_exe"]
 ,["f","PowerOff.cmd - Shortcut.lnk,.lnk,,,,bin_ptr"]
 ,["f","batch.lnk,.lnk,,,,bin_ptr"]
 ,["f","run-off.cmd.lnk,.lnk,,,,bin_ptr"]
 ,["f","run.mnu.lnk,.lnk,,,,bin_ptr"]
 ,["f","Start Menu [c progdata ms win].lnk,.lnk,,,,etc"]
 ,["f","run-apl.cmd.lnk,.lnk,,,,etc"]
 ,["f","run-hlp.cmd,.cmd,,,,etc"]
 ,["f","run-on.cmd.lnk,.lnk,,,,etc"]

 ,["k","#scr"] ,["p","scr"]
 ,["f","auth_paths.cmd,.cmd,,,,scr_cmd"]
 ,["f","go.cmd,.cmd,,,,scr_cmd"]
 ,["f","run.cmd,.cmd,,,,scr_cmd"]
 ,["f","set_GAP55A -.cmd,.cmd,,,,scr_cmd"]
 ,["f","set_canyon.cmd,.cmd,,,,scr_cmd"]
 ,["f","set_mordred.cmd,.cmd,,,,scr_cmd"]
 ,["f","sys.cmd,.cmd,,,,scr_cmd"]
 ,["f","sys-.js,.js,,,,web_cont"]
 ,["f","dump.cmd,.cmd,,,,etc"]
 ,["f","hlp.cmd,.cmd,,,,etc"]
 ,["f","run_apl.cmd,.cmd,,,,etc"]
 ,["f","set_GAP55A.cmd,.cmd,,,,etc"]
 ,["f","set_katrina.cmd,.cmd,,,,etc"]
 ,["f","set_thor.cmd,.cmd,,,,etc"]

 ,["k","log"] ,["p","log"]
 ,["f","CANYON-Elefter.log,.log,,,,txt_data"]
 ,["f","MORDRED-user.log,.log,,,,txt_data"]
 ,["f","GAP55A-Elefter -.csv,.csv,,,,txt_data"]
 ,["f","GAP55A-Elefter.csv,.csv,,,,etc"]
 ,["f","THOR-user.log,.log,,,,etc"]

 ,["n","boot-log"]
 ,["k","fld"] ,["p","boot-log"]
 ,["f","boot-log-.npp.ses,.ses,,,,ses"]
 ,["f","boot-log.npp.ses,.ses,,,,ses"]
 ,["f","boot-cfg.cmd,.cmd,,,,scr_cmd"]
 ,["f","boot-data-js.cmd,.cmd,,,,scr_cmd"]
 ,["f","boot-log.cmd,.cmd,,,,scr_cmd"]
 ,["f","copydata.cmd,.cmd,,,,scr_cmd"]
 ,["f","boot-log.hta,.hta,,,,scr_cmd"]
 ,["f","boot-log-.htm,.htm,,,,web_cont"]
 ,["f","boot-log.htm,.htm,,,,web_cont"]
 ,["f","boot-log-styles.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","CHOICE.COM,.com,,,,bin_exe"]
 ,["f","boot-chk.cmd,.cmd,,,,etc"]

 ,["k","data"] ,["p","data"]
 ,["f","boot-2008.js,.js,,,,web_cont"]
 ,["f","boot-2011.js,.js,,,,web_cont"]
 ,["f","boot-2012b.js,.js,,,,web_cont"]
 ,["f","boot-2013.js,.js,,,,web_cont"]
 ,["f","boot-2015.js,.js,,,,web_cont"]
 ,["f","boot-2020.js,.js,,,,web_cont"]
 ,["f","boot-2010.js,.js,,,,etc"]
 ,["f","boot-2012b.,.,,,,etc"]
 ,["f","boot-2013.,.,,,,etc"]
 ,["f","boot-2014.,.,,,,etc"]
 ,["f","boot-2015.,.,,,,etc"]
 ,["f","boot-2020.,.,,,,etc"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date-diff.js,.js,,,,web_cont"]
 ,["f","env.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","date.js,.js,,,,etc"]
 ,["f","root&load.js,.js,,,,etc"]

 ,["k","menu"] ,["p","menu"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","+hibern.lnk,.lnk,,,,bin_ptr"]
 ,["f","+logout.lnk,.lnk,,,,bin_ptr"]
 ,["f","+shutdown.lnk,.lnk,,,,bin_ptr"]
 ,["f","+switch.lnk,.lnk,,,,bin_ptr"]
 ,["f","-login.lnk,.lnk,,,,bin_ptr"]
 ,["f","boot-data-js.cmd.lnk,.lnk,,,,bin_ptr"]
 ,["f","+lock.lnk,.lnk,,,,etc"]
 ,["f","+restart.lnk,.lnk,,,,etc"]
 ,["f","+sleep.lnk,.lnk,,,,etc"]
 ,["f","-log2---.lnk,.lnk,,,,etc"]
 ,["f","-shutAbort!.lnk,.lnk,,,,etc"]

 ,["k","pics"] ,["p","pics"]
 ,["f","BTN_RUNTASK.ico,.ico,,,,bin_pic"]
 ,["f","INFO.ico,.ico,,,,bin_pic"]
 ,["f","LogOff+.ico,.ico,,,,bin_pic"]
 ,["f","REBOOT.ico,.ico,,,,bin_pic"]
 ,["f","Run-multi.ico,.ico,,,,bin_pic"]
 ,["f","SHUTDOWN-orange.ico,.ico,,,,bin_pic"]
 ,["f","autorun.ico,.ico,,,,bin_pic"]
 ,["f","clicknrun_grey.ico,.ico,,,,bin_pic"]
 ,["f","hibernate_nircmd.ico,.ico,,,,bin_pic"]
 ,["f","lock_nircmd.ico,.ico,,,,bin_pic"]
 ,["f","login-.ico,.ico,,,,bin_pic"]
 ,["f","logoff_nircmd.ico,.ico,,,,bin_pic"]
 ,["f","logout+.ico,.ico,,,,bin_pic"]
 ,["f","reboot2.ico,.ico,,,,bin_pic"]
 ,["f","run setup.ICO,.ico,,,,bin_pic"]
 ,["f","run-build-3.ico,.ico,,,,bin_pic"]
 ,["f","run-build.ico,.ico,,,,bin_pic"]
 ,["f","run-rebuild-2.ico,.ico,,,,bin_pic"]
 ,["f","shutdown2.ico,.ico,,,,bin_pic"]
 ,["f","standby_nircmd.ico,.ico,,,,bin_pic"]
 ,["f","system-shutdown.ico,.ico,,,,bin_pic"]
 ,["f","utilities-run.ico,.ico,,,,bin_pic"]
 ,["f","IDI_RUN.ico,.ico,,,,etc"]
 ,["f","LogOff aqua.ico,.ico,,,,etc"]
 ,["f","LogOff2 aqua.ico,.ico,,,,etc"]
 ,["f","Run blue.ico,.ico,,,,etc"]
 ,["f","Run.ico,.ico,,,,etc"]
 ,["f","TURNOFF.ico,.ico,,,,etc"]
 ,["f","clicknrun.ico,.ico,,,,etc"]
 ,["f","hibernate.ico,.ico,,,,etc"]
 ,["f","lock-yellow.ico,.ico,,,,etc"]
 ,["f","login+.ico,.ico,,,,etc"]
 ,["f","login.ico,.ico,,,,etc"]
 ,["f","logon.ico,.ico,,,,etc"]
 ,["f","logout-.ico,.ico,,,,etc"]
 ,["f","restart_nircmd.ico,.ico,,,,etc"]
 ,["f","run-build-2.ico,.ico,,,,etc"]
 ,["f","run-build-install.ico,.ico,,,,etc"]
 ,["f","run-cmd.ico,.ico,,,,etc"]
 ,["f","shutdown-red.ico,.ico,,,,etc"]
 ,["f","sleep.ico,.ico,,,,etc"]
 ,["f","system-shutdown-rnd.ico,.ico,,,,etc"]
 ,["f","turnoff_nircmd.ico,.ico,,,,etc"]

 ,["k","prog"] ,["p","prog"]
 ,["f","PowerLink.exe,.exe,,,,bin_exe"]
 ,["f","logoff.exe.lnk,.lnk,,,,bin_ptr"]
 ,["f","logoff.exe,.exe,,,,etc"]

 ,["k","js"] ,["p","scr"]
 ,["f","boot-LOGshow.js,.js,,,,web_cont"]
 ,["f","boot-hdr.js,.js,,,,web_cont"]
 ,["f","boot-log-win-set.js,.js,,,,web_cont"]
 ,["f","boot-log..proj-list.js,.js,,,,web_cont"]
 ,["f","proj-list..media.js,.js,,,,web_cont"]
 ,["f","boot-ftr.js,.js,,,,etc"]
 ,["f","boot-log-lists.js,.js,,,,etc"]
 ,["f","boot-log-win.js,.js,,,,etc"]
 ,["f","proj-list boot-log.js,.js,,,,etc"]

 ,["n","Bible-bg.13"]
 ,["k","fld"] ,["p","Bible-bg/Bible-bg.2013"]
 ,["f","Bible-bg.hta,.hta,,,,scr_cmd"]
 ,["f","bible-bg reformat.hta,.hta,,,,scr_cmd"]
 ,["f","index.Bible-bg.2013.htm,.htm,,,,web_cont"]
 ,["f","paths.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","paths.js.lnk,.lnk,,,,bin_ptr"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]

 ,["k","scr "] ,["p","scr"]
 ,["f","album-ikoni.js,.js,,,,web_cont"]
 ,["f","ar2obj.js,.js,,,,web_cont"]
 ,["f","bible.js,.js,,,,web_cont"]
 ,["f","colors.js,.js,,,,web_cont"]
 ,["f","findres.js,.js,,,,web_cont"]
 ,["f","kalendar cfg.js,.js,,,,web_cont"]
 ,["f","kalendar.js,.js,,,,web_cont"]
 ,["f","links.js,.js,,,,web_cont"]
 ,["f","nt-hdr.js,.js,,,,web_cont"]
 ,["f","ot-hdr.js,.js,,,,web_cont"]
 ,["f","outfmt.js,.js,,,,web_cont"]
 ,["f","pesah.js,.js,,,,web_cont"]
 ,["f","utils.js,.js,,,,web_cont"]
 ,["f","words.js,.js,,,,web_cont"]
 ,["f","Bible-bg.css,.css,,,,web_cont"]
 ,["f","album.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","arrdef.js,.js,,,,etc"]
 ,["f","clock.js,.js,,,,etc"]
 ,["f","control.js,.js,,,,etc"]
 ,["f","findtt.js,.js,,,,etc"]
 ,["f","kalendar hdr.js,.js,,,,etc"]
 ,["f","layout.js,.js,,,,etc"]
 ,["f","loader.js,.js,,,,etc"]
 ,["f","nt.words.js,.js,,,,etc"]
 ,["f","ot.words.js,.js,,,,etc"]
 ,["f","pages.js,.js,,,,etc"]
 ,["f","show.js,.js,,,,etc"]
 ,["f","web-colors.js,.js,,,,etc"]

 ,["n","Bible-bg.10"]
 ,["k","fld"] ,["p","Bible-bg/Bible-bg.2010"]
 ,["f","index.Bible-bg.10.html,.html,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","Bible-BG.ucoz.ru.URL,.url,,,,web_ptr"]
 ,["f","HTML Color Picker.URL,.url,,,,web_ptr"]
 ,["f","bible-bg@prism.app.lnk,.lnk,,,,bin_ptr"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]

 ,["k","#cont"] ,["p","content"]
 ,["f","about.htm,.htm,,,,web_cont"]
 ,["f","biblist.htm,.htm,,,,web_cont"]
 ,["f","bibtheme.htm,.htm,,,,web_cont"]
 ,["f","books.htm,.htm,,,,web_cont"]
 ,["f","empty.htm,.htm,,,,web_cont"]
 ,["f","find.htm,.htm,,,,web_cont"]
 ,["f","index.htm,.htm,,,,web_cont"]
 ,["f","links.htm,.htm,,,,web_cont"]
 ,["f","menu.htm,.htm,,,,web_cont"]
 ,["f","system.htm,.htm,,,,web_cont"]
 ,["f","welcome.htm,.htm,,,,web_cont"]
 ,["f","bib_win.js,.js,,,,web_cont"]
 ,["f","biblist.js,.js,,,,web_cont"]
 ,["f","cfg.js,.js,,,,web_cont"]
 ,["f","find.js,.js,,,,web_cont"]
 ,["f","idxgen.js,.js,,,,web_cont"]
 ,["f","links.js,.js,,,,web_cont"]
 ,["f","show.js,.js,,,,web_cont"]
 ,["f","utils.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","#.txt,.txt,,,,txt_data"]
 ,["f","about.txt,.txt,,,,txt_data"]
 ,["f","err.txt,.txt,,,,txt_data"]
 ,["f","todo.txt,.txt,,,,txt_data"]
 ,["f","[semin] project.txt,.txt,,,,etc"]
 ,["f","bible-bg.projinfo.txt,.txt,,,,etc"]
 ,["f","bibtheme.js,.js,,,,etc"]
 ,["f","files.txt,.txt,,,,etc"]
 ,["f","findres.js,.js,,,,etc"]
 ,["f","info.js,.js,,,,etc"]
 ,["f","load-call.js,.js,,,,etc"]
 ,["f","show.htm,.htm,,,,etc"]
 ,["f","zasto.txt,.txt,,,,etc"]

 ,["k","#fmt"] ,["p","content/fmt"]
 ,["f","reformat.hta,.hta,,,,scr_cmd"]
 ,["f","formater.js,.js,,,,web_cont"]
 ,["f","outfmt2.js,.js,,,,web_cont"]
 ,["f","outfmt.js,.js,,,,etc"]

 ,["k","#index"] ,["p","content/index"]
 ,["f","test-bnm.htm,.htm,,,,web_cont"]
 ,["f","hdr-short.js,.js,,,,web_cont"]
 ,["f","nt-hdr.js,.js,,,,web_cont"]
 ,["f","ot-hdr.js,.js,,,,web_cont"]
 ,["f","nt-arrdef.js,.js,,,,etc"]
 ,["f","ot-arrdef.js,.js,,,,etc"]

 ,["k","text"] ,["p","content/text"]
 ,["f","NT.bg.js,.js,,,,web_cont"]
 ,["f","OT.bg.js,.js,,,,etc"]

 ,["k","#words"] ,["p","content/words"]
 ,["f","Bible-BG.words.htm,.htm,,,,web_cont"]
 ,["f","words.htm,.htm,,,,web_cont"]
 ,["f","NT.words.js,.js,,,,web_cont"]
 ,["f","words.js,.js,,,,web_cont"]
 ,["f","OT.words.js,.js,,,,etc"]

 ,["k","#xml"] ,["p","content/xml"]
 ,["f","Bible-BG load.xml.htm,.htm,,,,web_cont"]
 ,["f","zxml.js,.js,,,,web_cont"]
 ,["f","Bible-BG loadNT-.htm,.htm,,,,etc"]

 ,["k","#album"] ,["p","content/album"]
 ,["f","album-ikoni.htm,.htm,,,,web_cont"]
 ,["f","album-ikoni.js,.js,,,,web_cont"]

 ,["k","#clock"] ,["p","content/clock"]
 ,["f","test clock.htm,.htm,,,,web_cont"]
 ,["f","clock.js,.js,,,,web_cont"]
 ,["f","clock0.js,.js,,,,etc"]

 ,["k","#color"] ,["p","content/color"]
 ,["f","colors.htm,.htm,,,,web_cont"]
 ,["f","colors.js,.js,,,,web_cont"]
 ,["f","Bible-bg.css,.css,,,,web_cont"]
 ,["f","album.css,.css,,,,web_cont"]
 ,["f","Bible-bg.xml.css,.css,,,,etc"]
 ,["f","web-colors.js,.js,,,,etc"]

 ,["k","#kal"] ,["p","content/kalendar"]
 ,["f","history.htm,.htm,,,,web_cont"]
 ,["f","kalendar-y.htm,.htm,,,,web_cont"]
 ,["f","Pesah.js,.js,,,,web_cont"]
 ,["f","kalendar cfg.js,.js,,,,web_cont"]
 ,["f","kalendar.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","kal.ico,.ico,,,,bin_pic"]
 ,["f","kalendar hdr.js,.js,,,,etc"]

 ,["k","#nt.pg"] ,["p","content/nt.pg"]
 ,["f","Bible-BG.10GodCom.htm,.htm,,,,web_cont"]
 ,["f","Bible-BG.NT-beatitudes.htm,.htm,,,,web_cont"]
 ,["f","Bible-BG.NT-prayers.htm,.htm,,,,web_cont"]
 ,["f","Bible-BG.NT-FaithSymbol.htm,.htm,,,,etc"]
 ,["f","Bible-BG.NT-holydays.htm,.htm,,,,etc"]

 ,["n","Bible-bg.09"]
 ,["k","fld"] ,["p","Bible-bg/Bible-bg.2009"]
 ,["f","Bible-bg.hta,.hta,,,,scr_cmd"]
 ,["f","bible-bg reformat.hta,.hta,,,,scr_cmd"]
 ,["f","Bible-bg.NT-FaithSymbol.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.NT-holydays.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.OT-10GodCom.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.biblist.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.control.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.find.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.ikons-album.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.links.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.show.htm,.htm,,,,web_cont"]
 ,["f","Bible-bg.web-clr.htm,.htm,,,,web_cont"]
 ,["f","fb.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","bsbible.zip Библията, издадена от Светия Синод на Българската църква..URL,.url,,,,web_ptr"]
 ,["f","Иоан.13.34-35 @.URL,.url,,,,web_ptr"]
 ,["f","Bible-bg.09 (2).lnk,.lnk,,,,bin_ptr"]
 ,["f","Bible-bg w.ico,.ico,,,,bin_pic"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]
 ,["f","Bible-bg.09.lnk,.lnk,,,,etc"]
 ,["f","Bible-bg.NT-beatitudes.htm,.htm,,,,etc"]
 ,["f","Bible-bg.NT-prayers.htm,.htm,,,,etc"]
 ,["f","Bible-bg.about.htm,.htm,,,,etc"]
 ,["f","Bible-bg.books.htm,.htm,,,,etc"]
 ,["f","Bible-bg.control.htm.bak,.bak,,,,etc"]
 ,["f","Bible-bg.history.htm,.htm,,,,etc"]
 ,["f","Bible-bg.kalendar-y.htm,.htm,,,,etc"]
 ,["f","Bible-bg.menu.htm,.htm,,,,etc"]
 ,["f","Bible-bg.themes.htm,.htm,,,,etc"]
 ,["f","Bible-bg.welcome.htm,.htm,,,,etc"]
 ,["f","index.Bible-bg.09.htm,.htm,,,,etc"]
 ,["f","Иоан.13.34-35 ^.URL,.URL,,,,etc"]

 ,["k","scr "] ,["p","scr"]
 ,["f","activex.js,.js,,,,web_cont"]
 ,["f","arrdef.js,.js,,,,web_cont"]
 ,["f","bibtheme.js,.js,,,,web_cont"]
 ,["f","clock.js,.js,,,,web_cont"]
 ,["f","control.js,.js,,,,web_cont"]
 ,["f","findtt.js,.js,,,,web_cont"]
 ,["f","info.js,.js,,,,web_cont"]
 ,["f","kalendar hdr.js,.js,,,,web_cont"]
 ,["f","links.js,.js,,,,web_cont"]
 ,["f","nt.words.js,.js,,,,web_cont"]
 ,["f","ot.words.js,.js,,,,web_cont"]
 ,["f","pesah.js,.js,,,,web_cont"]
 ,["f","show.js,.js,,,,web_cont"]
 ,["f","web-colors.js,.js,,,,web_cont"]
 ,["f","xhtm2js.js,.js,,,,web_cont"]
 ,["f","Bible-BG.css,.css,,,,web_cont"]
 ,["f","album.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","album-ikoni.js,.js,,,,etc"]
 ,["f","biblist.js,.js,,,,etc"]
 ,["f","cfg.js,.js,,,,etc"]
 ,["f","colors.js,.js,,,,etc"]
 ,["f","findres.js,.js,,,,etc"]
 ,["f","idx.js,.js,,,,etc"]
 ,["f","kalendar cfg.js,.js,,,,etc"]
 ,["f","kalendar.js,.js,,,,etc"]
 ,["f","nt-hdr.js,.js,,,,etc"]
 ,["f","ot-hdr.js,.js,,,,etc"]
 ,["f","outfmt.js,.js,,,,etc"]
 ,["f","runerr.js,.js,,,,etc"]
 ,["f","utils.js,.js,,,,etc"]
 ,["f","words.js,.js,,,,etc"]

 ,["n","Bible icons"]
 ,["k","fld"] ,["p","Bible-bg/Bible-bg.icons"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]
 ,["f","HristosPantokrator.jpg,.jpg,,,,bin_pic"]
 ,["f","RojdestvoHristovo.jpg,.jpg,,,,bin_pic"]
 ,["f","Sv Georgi.jpg,.jpg,,,,bin_pic"]
 ,["f","arh.Serafim Sobolev.jpg,.jpg,,,,bin_pic"]
 ,["f","sv.Bogorodica.jpg,.jpg,,,,bin_pic"]
 ,["f","sv.IvanRilski.jpg,.jpg,,,,bin_pic"]
 ,["f","ISUS2.jpg,.jpg,,,,etc"]
 ,["f","Sofia,Viara Nadejda,Ljubov.jpg,.jpg,,,,etc"]
 ,["f","Sv Nikolai.jpg,.jpg,,,,etc"]
 ,["f","sv.Bogorodica Jerusalem.jpg,.jpg,,,,etc"]
 ,["f","sv.Georgi 2.jpg,.jpg,,,,etc"]
 ,["f","sv.Mina.jpg,.jpg,,,,etc"]

 ,["n","Bible-bg text"]
 ,["k","fld"] ,["p","Bible-bg/Bible-bg.text"]
 ,["f","chapter-20.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-22.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-24.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-26.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-28.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-30.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-32.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-34.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-36.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-38.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-40.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-42.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-44.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-46.xhtml,.xhtml,,,,web_cont"]
 ,["f","chapter-48.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-01.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-03.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-05.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-07.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-09.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-11.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-13.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-15.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-17.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-19.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-21.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-23.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-25.xhtml,.xhtml,,,,web_cont"]
 ,["f","nt-27.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-01.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-03.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-05.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-07.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-09.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-11.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-13.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-15.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-17.xhtml,.xhtml,,,,web_cont"]
 ,["f","ot-19.xhtml,.xhtml,,,,web_cont"]
 ,["f","NT-01.bg.js,.js,,,,web_cont"]
 ,["f","NT-03.bg.js,.js,,,,web_cont"]
 ,["f","NT-05.bg.js,.js,,,,web_cont"]
 ,["f","NT-07.bg.js,.js,,,,web_cont"]
 ,["f","NT-09.bg.js,.js,,,,web_cont"]
 ,["f","NT-11.bg.js,.js,,,,web_cont"]
 ,["f","NT-13.bg.js,.js,,,,web_cont"]
 ,["f","NT-15.bg.js,.js,,,,web_cont"]
 ,["f","NT-17.bg.js,.js,,,,web_cont"]
 ,["f","NT-19.bg.js,.js,,,,web_cont"]
 ,["f","NT-21.bg.js,.js,,,,web_cont"]
 ,["f","NT-23.bg.js,.js,,,,web_cont"]
 ,["f","NT-25.bg.js,.js,,,,web_cont"]
 ,["f","NT-27.bg.js,.js,,,,web_cont"]
 ,["f","NT.words.js,.js,,,,web_cont"]
 ,["f","OT-02.bg.js,.js,,,,web_cont"]
 ,["f","OT-04.bg.js,.js,,,,web_cont"]
 ,["f","OT-06.bg.js,.js,,,,web_cont"]
 ,["f","OT-08.bg.js,.js,,,,web_cont"]
 ,["f","OT-10.bg.js,.js,,,,web_cont"]
 ,["f","OT-12.bg.js,.js,,,,web_cont"]
 ,["f","OT-14.bg.js,.js,,,,web_cont"]
 ,["f","OT-16.bg.js,.js,,,,web_cont"]
 ,["f","OT-18.bg.js,.js,,,,web_cont"]
 ,["f","OT-20.bg.js,.js,,,,web_cont"]
 ,["f","OT-22.bg.js,.js,,,,web_cont"]
 ,["f","OT-24.bg.js,.js,,,,web_cont"]
 ,["f","OT-26.bg.js,.js,,,,web_cont"]
 ,["f","OT-28.bg.js,.js,,,,web_cont"]
 ,["f","OT-30.bg.js,.js,,,,web_cont"]
 ,["f","OT-32.bg.js,.js,,,,web_cont"]
 ,["f","OT-34.bg.js,.js,,,,web_cont"]
 ,["f","OT-36.bg.js,.js,,,,web_cont"]
 ,["f","OT-38.bg.js,.js,,,,web_cont"]
 ,["f","OT-40.bg.js,.js,,,,web_cont"]
 ,["f","OT-42.bg.js,.js,,,,web_cont"]
 ,["f","OT-44.bg.js,.js,,,,web_cont"]
 ,["f","OT-46.bg.js,.js,,,,web_cont"]
 ,["f","OT-48.bg.js,.js,,,,web_cont"]
 ,["f","OT-50.bg.js,.js,,,,web_cont"]
 ,["f","OT.words.js,.js,,,,web_cont"]
 ,["f","main.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","Bible-##.js.zip,.zip,,,,bin_arch"]
 ,["f","nt.epub,.epub,,,,bin_publ"]
 ,["f","ot.epub,.epub,,,,bin_publ"]
 ,["f","NT.spell.rtf,.rtf,,,,bin_publ"]
 ,["f","OT.spell.rtf,.rtf,,,,bin_publ"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]
 ,["f","NT-02.bg.js,.js,,,,etc"]
 ,["f","NT-04.bg.js,.js,,,,etc"]
 ,["f","NT-06.bg.js,.js,,,,etc"]
 ,["f","NT-08.bg.js,.js,,,,etc"]
 ,["f","NT-10.bg.js,.js,,,,etc"]
 ,["f","NT-12.bg.js,.js,,,,etc"]
 ,["f","NT-14.bg.js,.js,,,,etc"]
 ,["f","NT-16.bg.js,.js,,,,etc"]
 ,["f","NT-18.bg.js,.js,,,,etc"]
 ,["f","NT-20.bg.js,.js,,,,etc"]
 ,["f","NT-22.bg.js,.js,,,,etc"]
 ,["f","NT-24.bg.js,.js,,,,etc"]
 ,["f","NT-26.bg.js,.js,,,,etc"]
 ,["f","NT.js,.js,,,,etc"]
 ,["f","OT-01.bg.js,.js,,,,etc"]
 ,["f","OT-03.bg.js,.js,,,,etc"]
 ,["f","OT-05.bg.js,.js,,,,etc"]
 ,["f","OT-07.bg.js,.js,,,,etc"]
 ,["f","OT-09.bg.js,.js,,,,etc"]
 ,["f","OT-11.bg.js,.js,,,,etc"]
 ,["f","OT-13.bg.js,.js,,,,etc"]
 ,["f","OT-15.bg.js,.js,,,,etc"]
 ,["f","OT-17.bg.js,.js,,,,etc"]
 ,["f","OT-19.bg.js,.js,,,,etc"]
 ,["f","OT-21.bg.js,.js,,,,etc"]
 ,["f","OT-23.bg.js,.js,,,,etc"]
 ,["f","OT-25.bg.js,.js,,,,etc"]
 ,["f","OT-27.bg.js,.js,,,,etc"]
 ,["f","OT-29.bg.js,.js,,,,etc"]
 ,["f","OT-31.bg.js,.js,,,,etc"]
 ,["f","OT-33.bg.js,.js,,,,etc"]
 ,["f","OT-35.bg.js,.js,,,,etc"]
 ,["f","OT-37.bg.js,.js,,,,etc"]
 ,["f","OT-39.bg.js,.js,,,,etc"]
 ,["f","OT-41.bg.js,.js,,,,etc"]
 ,["f","OT-43.bg.js,.js,,,,etc"]
 ,["f","OT-45.bg.js,.js,,,,etc"]
 ,["f","OT-47.bg.js,.js,,,,etc"]
 ,["f","OT-49.bg.js,.js,,,,etc"]
 ,["f","OT.js,.js,,,,etc"]
 ,["f","chapter-21.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-23.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-25.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-27.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-29.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-31.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-33.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-35.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-37.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-39.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-41.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-43.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-45.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-47.xhtml,.xhtml,,,,etc"]
 ,["f","chapter-49.xhtml,.xhtml,,,,etc"]
 ,["f","nt-02.xhtml,.xhtml,,,,etc"]
 ,["f","nt-04.xhtml,.xhtml,,,,etc"]
 ,["f","nt-06.xhtml,.xhtml,,,,etc"]
 ,["f","nt-08.xhtml,.xhtml,,,,etc"]
 ,["f","nt-10.xhtml,.xhtml,,,,etc"]
 ,["f","nt-12.xhtml,.xhtml,,,,etc"]
 ,["f","nt-14.xhtml,.xhtml,,,,etc"]
 ,["f","nt-16.xhtml,.xhtml,,,,etc"]
 ,["f","nt-18.xhtml,.xhtml,,,,etc"]
 ,["f","nt-20.xhtml,.xhtml,,,,etc"]
 ,["f","nt-22.xhtml,.xhtml,,,,etc"]
 ,["f","nt-24.xhtml,.xhtml,,,,etc"]
 ,["f","nt-26.xhtml,.xhtml,,,,etc"]
 ,["f","ot-02.xhtml,.xhtml,,,,etc"]
 ,["f","ot-04.xhtml,.xhtml,,,,etc"]
 ,["f","ot-06.xhtml,.xhtml,,,,etc"]
 ,["f","ot-08.xhtml,.xhtml,,,,etc"]
 ,["f","ot-10.xhtml,.xhtml,,,,etc"]
 ,["f","ot-12.xhtml,.xhtml,,,,etc"]
 ,["f","ot-14.xhtml,.xhtml,,,,etc"]
 ,["f","ot-16.xhtml,.xhtml,,,,etc"]
 ,["f","ot-18.xhtml,.xhtml,,,,etc"]
 ,["f","ot-20.xhtml,.xhtml,,,,etc"]

 ,["n","Bible text"]
 ,["k","fld"] ,["p","Bible-bg/Bible.text"]
 ,["f","NT-01.bg.js,.js,,,,web_cont"]
 ,["f","NT-03.bg.js,.js,,,,web_cont"]
 ,["f","NT-05.bg.js,.js,,,,web_cont"]
 ,["f","NT-07.bg.js,.js,,,,web_cont"]
 ,["f","NT-09.bg.js,.js,,,,web_cont"]
 ,["f","NT-11.bg.js,.js,,,,web_cont"]
 ,["f","NT-13.bg.js,.js,,,,web_cont"]
 ,["f","NT-15.bg.js,.js,,,,web_cont"]
 ,["f","NT-17.bg.js,.js,,,,web_cont"]
 ,["f","NT-19.bg.js,.js,,,,web_cont"]
 ,["f","NT-21.bg.js,.js,,,,web_cont"]
 ,["f","NT-23.bg.js,.js,,,,web_cont"]
 ,["f","NT-25.bg.js,.js,,,,web_cont"]
 ,["f","NT-27.bg.js,.js,,,,web_cont"]
 ,["f","NT.words-.js,.js,,,,web_cont"]
 ,["f","OT-01.bg.js,.js,,,,web_cont"]
 ,["f","OT-03.bg.js,.js,,,,web_cont"]
 ,["f","OT-05.bg.js,.js,,,,web_cont"]
 ,["f","OT-07.bg.js,.js,,,,web_cont"]
 ,["f","OT-09.bg.js,.js,,,,web_cont"]
 ,["f","OT-11.bg.js,.js,,,,web_cont"]
 ,["f","OT-13.bg.js,.js,,,,web_cont"]
 ,["f","OT-15.bg.js,.js,,,,web_cont"]
 ,["f","OT-17.bg.js,.js,,,,web_cont"]
 ,["f","OT-19.bg.js,.js,,,,web_cont"]
 ,["f","OT-21.bg.js,.js,,,,web_cont"]
 ,["f","OT-23.bg.js,.js,,,,web_cont"]
 ,["f","OT-25.bg.js,.js,,,,web_cont"]
 ,["f","OT-27.bg.js,.js,,,,web_cont"]
 ,["f","OT-29.bg.js,.js,,,,web_cont"]
 ,["f","OT-31.bg.js,.js,,,,web_cont"]
 ,["f","OT-33.bg.js,.js,,,,web_cont"]
 ,["f","OT-35.bg.js,.js,,,,web_cont"]
 ,["f","OT-37.bg.js,.js,,,,web_cont"]
 ,["f","OT-39.bg.js,.js,,,,web_cont"]
 ,["f","OT-41.bg.js,.js,,,,web_cont"]
 ,["f","OT-43.bg.js,.js,,,,web_cont"]
 ,["f","OT-45.bg.js,.js,,,,web_cont"]
 ,["f","OT-47.bg.js,.js,,,,web_cont"]
 ,["f","OT-49.bg.js,.js,,,,web_cont"]
 ,["f","OT.js,.js,,,,web_cont"]
 ,["f","OT.words.js,.js,,,,web_cont"]
 ,["f","main.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","NT.words.log,.log,,,,txt_data"]
 ,["f","OT.words.log,.log,,,,txt_data"]
 ,["f","Bible-bg.ico,.ico,,,,bin_pic"]
 ,["f","NT-02.bg.js,.js,,,,etc"]
 ,["f","NT-04.bg.js,.js,,,,etc"]
 ,["f","NT-06.bg.js,.js,,,,etc"]
 ,["f","NT-08.bg.js,.js,,,,etc"]
 ,["f","NT-10.bg.js,.js,,,,etc"]
 ,["f","NT-12.bg.js,.js,,,,etc"]
 ,["f","NT-14.bg.js,.js,,,,etc"]
 ,["f","NT-16.bg.js,.js,,,,etc"]
 ,["f","NT-18.bg.js,.js,,,,etc"]
 ,["f","NT-20.bg.js,.js,,,,etc"]
 ,["f","NT-22.bg.js,.js,,,,etc"]
 ,["f","NT-24.bg.js,.js,,,,etc"]
 ,["f","NT-26.bg.js,.js,,,,etc"]
 ,["f","NT.js,.js,,,,etc"]
 ,["f","NT.words.js,.js,,,,etc"]
 ,["f","OT-02.bg.js,.js,,,,etc"]
 ,["f","OT-04.bg.js,.js,,,,etc"]
 ,["f","OT-06.bg.js,.js,,,,etc"]
 ,["f","OT-08.bg.js,.js,,,,etc"]
 ,["f","OT-10.bg.js,.js,,,,etc"]
 ,["f","OT-12.bg.js,.js,,,,etc"]
 ,["f","OT-14.bg.js,.js,,,,etc"]
 ,["f","OT-16.bg.js,.js,,,,etc"]
 ,["f","OT-18.bg.js,.js,,,,etc"]
 ,["f","OT-20.bg.js,.js,,,,etc"]
 ,["f","OT-22.bg.js,.js,,,,etc"]
 ,["f","OT-24.bg.js,.js,,,,etc"]
 ,["f","OT-26.bg.js,.js,,,,etc"]
 ,["f","OT-28.bg.js,.js,,,,etc"]
 ,["f","OT-30.bg.js,.js,,,,etc"]
 ,["f","OT-32.bg.js,.js,,,,etc"]
 ,["f","OT-34.bg.js,.js,,,,etc"]
 ,["f","OT-36.bg.js,.js,,,,etc"]
 ,["f","OT-38.bg.js,.js,,,,etc"]
 ,["f","OT-40.bg.js,.js,,,,etc"]
 ,["f","OT-42.bg.js,.js,,,,etc"]
 ,["f","OT-44.bg.js,.js,,,,etc"]
 ,["f","OT-46.bg.js,.js,,,,etc"]
 ,["f","OT-48.bg.js,.js,,,,etc"]
 ,["f","OT-50.bg.js,.js,,,,etc"]
 ,["f","OT.words-.js,.js,,,,etc"]

 ,["n","X14"]
 ,["k","fld"] ,["p","x14"]
 ,["f","x14.npp.ses,.ses,,,,ses"]
 ,["f","x14.files.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","x14.lst,.lst,,,,txt_data"]
 ,["f","x14.md5,.md5,,,,txt_data"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]

 ,["k","run"] ,["p","run"]
 ,["f","x-widget.hta,.hta,,,,scr_cmd"]
 ,["f","x-mnu.htm,.htm,,,,web_cont"]
 ,["f","x-cfg.js,.js,,,,web_cont"]
 ,["f","x-widget.htm,.htm,,,,etc"]

 ,["n","X14-cal"]
 ,["k","fld"] ,["p","x14"]
 ,["f","x14.npp.ses,.ses,,,,ses"]
 ,["f","x14.files.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","x14.lst,.lst,,,,txt_data"]
 ,["f","x14.md5,.md5,,,,txt_data"]

 ,["k","cal"] ,["p","cal"]
 ,["f","calendar-.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","kalendar#1,3,1.URL,.url,,,,web_ptr"]
 ,["f","kal.ico,.ico,,,,bin_pic"]
 ,["f","calendar.htm,.htm,,,,etc"]
 ,["f","kalendar.URL,.URL,,,,etc"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]

 ,["k","scr"] ,["p","cal/scr"]
 ,["f","calendar-cfg.js,.js,,,,web_cont"]
 ,["f","calendar-show.js,.js,,,,web_cont"]
 ,["f","cal-style-0.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","cal-style-1.css,.css,,,,etc"]
 ,["f","calendar-hdr.js,.js,,,,etc"]

 ,["k","run"] ,["p","run/run.cal"]
 ,["f","calendar-mhor-bl.hta,.hta,,,,scr_cmd"]
 ,["f","calendar-yhor.hta,.hta,,,,scr_cmd"]
 ,["f","calendar-ystd.hta,.hta,,,,scr_cmd"]
 ,["f","kalendar-ylb.hta,.hta,,,,scr_cmd"]
 ,["f","kalendar-y.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","kalendar-1.zip,.zip,,,,bin_arch"]
 ,["f","calendar-mstd.hta,.hta,,,,etc"]
 ,["f","calendar-ystd-ask.hta,.hta,,,,etc"]
 ,["f","calendar.hta,.hta,,,,etc"]

 ,["n","X14-clk"]
 ,["k","fld"] ,["p","x14"]
 ,["f","x14.npp.ses,.ses,,,,ses"]
 ,["f","x14.files.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","x14.lst,.lst,,,,txt_data"]
 ,["f","x14.md5,.md5,,,,txt_data"]

 ,["k","clk"] ,["p","clk"]
 ,["f","clock-24.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","clock.ico,.ico,,,,bin_pic"]
 ,["f","timer.ico,.ico,,,,etc"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]

 ,["k","scr"] ,["p","clk/scr"]
 ,["f","clock.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]

 ,["k","run"] ,["p","run/run.clk"]
 ,["f","clock-24.hta,.hta,,,,scr_cmd"]

 ,["n","X14-drv"]
 ,["k","fld"] ,["p","x14"]
 ,["f","x14.npp.ses,.ses,,,,ses"]
 ,["f","x14.files.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","x14.lst,.lst,,,,txt_data"]
 ,["f","x14.md5,.md5,,,,txt_data"]

 ,["k","drv"] ,["p","drv"]
 ,["f","drv-info.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","d.ico,.ico,,,,bin_pic"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]

 ,["k","scr"] ,["p","drv/scr"]
 ,["f","addDrv.js,.js,,,,web_cont"]
 ,["f","drv-info.js,.js,,,,web_cont"]
 ,["f","fs.js,.js,,,,web_cont"]
 ,["f","drv-info-1.css,.css,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs-data.js,.js,,,,etc"]
 ,["f","makeTbl.js,.js,,,,etc"]

 ,["k","run"] ,["p","run/run.drv"]
 ,["f","drv-info+.hta,.hta,,,,scr_cmd"]
 ,["f","drv-info.3.hta,.hta,,,,scr_cmd"]
 ,["f","drv-info.3b.hta,.hta,,,,scr_cmd"]
 ,["f","drv-info.run.hta,.hta,,,,scr_cmd"]
 ,["f","drv-info--.htm,.htm,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","drv-info.3a.hta,.hta,,,,etc"]
 ,["f","drv-info.4.hta,.hta,,,,etc"]

 ,["n","X14-icard"]
 ,["k","fld"] ,["p","x14"]
 ,["f","x14.npp.ses,.ses,,,,ses"]
 ,["f","x14.files.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","x14.lst,.lst,,,,txt_data"]
 ,["f","x14.md5,.md5,,,,txt_data"]

 ,["k","icrd"] ,["p","icard"]
 ,["f","icard-ea.htm,.htm,,,,web_cont"]
 ,["f","ea-k.ico,.ico,,,,bin_pic"]
 ,["f","ea-w.ico,.ico,,,,etc"]

 ,["k","lib"] ,["p","lib"]
 ,["f","date.js,.js,,,,web_cont"]
 ,["f","loader.js,.js,,,,web_cont"]
 ,["f","windows.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","fs.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]

 ,["n","dirlist"]
 ,["k","fld"] ,["p","dirlist"]
 ,["f","dirlist.npp.ses,.ses,,,,ses"]
 ,["f","dirlist.cmd,.cmd,,,,scr_cmd"]
 ,["f","dirlist.hta,.hta,,,,scr_cmd"]
 ,["f","dirlist.htm,.htm,,,,web_cont"]
 ,["f","dirlist.files.js,.js,,,,web_cont"]
 ,["f","dirlist.lst,.lst,,,,txt_data"]
 ,["f","dirlist.md5,.md5,,,,txt_data"]
 ,["f","dirlist.zip,.zip,,,,bin_arch"]
 ,["f","dirlist ^.lnk,.lnk,,,,bin_ptr"]
 ,["f","foldlist.ico,.ico,,,,bin_pic"]

 ,["n","fs.menu-csv"]
 ,["k","fld"] ,["p","fs.menu-csv"]
 ,["f","fs.menu-csv.npp.ses,.ses,,,,ses"]
 ,["f","menu-csv.hta,.hta,,,,scr_cmd"]
 ,["f","menu-csv.htm,.htm,,,,web_cont"]
 ,["f","menu.csv.files.js,.js,,,,web_cont"]
 ,["f","menu-styles.css,.css,,,,web_cont"]
 ,["f","desktop.ini,.ini,,,,txt_data"]
 ,["f","menu-csv.lst,.lst,,,,txt_data"]
 ,["f","menu-csv.md5,.md5,,,,txt_data"]
 ,["f","menu-csv.zip,.zip,,,,bin_arch"]

 ,["k","data"] ,["p","data"]
 ,["f","menu+.csv.js,.js,,,,web_cont"]
 ,["f","menu-.csv.js,.js,,,,etc"]

 ,["n","drv-info.4"]
 ,["k","fld"] ,["p","drv-info.4"]
 ,["f","drv-info.4.npp.ses,.ses,,,,ses"]
 ,["f","drv-info.4.hta,.hta,,,,scr_cmd"]
 ,["f","drv-info.4.htm,.htm,,,,web_cont"]
 ,["f","activex-ie.js,.js,,,,web_cont"]
 ,["f","char-size.js,.js,,,,web_cont"]
 ,["f","drv-info.files.js,.js,,,,web_cont"]
 ,["f","order.js,.js,,,,web_cont"]
 ,["f","window.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","drv-info.4.lst,.lst,,,,txt_data"]
 ,["f","drv-info.4.md5,.md5,,,,txt_data"]
 ,["f","drv-info.4.zip,.zip,,,,bin_arch"]
 ,["f","D.ico,.ico,,,,bin_pic"]
 ,["f","browserid.js,.js,,,,etc"]
 ,["f","colors.js,.js,,,,etc"]
 ,["f","math.js,.js,,,,etc"]
 ,["f","time.js,.js,,,,etc"]

 ,["n","drv-log"]
 ,["k","fld"] ,["p","drv-log"]
 ,["f","drv-log.npp.ses,.ses,,,,ses"]
 ,["f","drv-log.hta,.hta,,,,scr_cmd"]
 ,["f","drv-log.htm,.htm,,,,web_cont"]
 ,["f","drv-log.data.js,.js,,,,web_cont"]
 ,["f","Desktop.ini,.ini,,,,txt_data"]
 ,["f","D.ico,.ico,,,,bin_pic"]
 ,["f","drv-log.fmt.js,.js,,,,etc"]

]
