outlog_('>>>ea-2010.js');Fnt=[// #[Type,Style, PathNo,SetNo,Win,PS,File,Flag,Bad, RWin,RPs,RStWin,RStPs]
/*0*/ ["M","N",0,0,"TektoMM","TektonMM","ZJRG____.MMM","*",0,0,0,"-","-"]
/*1*/,["M","I",0,0,"TektoMM","TektonMM-Oblique","ZJI_____.MMM","*",0,0,0,"-","-"]
/*2*/,["1","N",1,1,"Symbol","Symbol","SY______.PFM","*",0,0,0,"-","-"]
/*3*/,["T","N",2,2,"Bwgrkn","bwgrkn","Bwgrkn.ttf","*",0,0,0,"-","-"]
/*4*/,["T","N",2,2,"Coptic","CopticMedium","Coptic Medium.ttf","*",0,0,0,"-","-"]
/*5*/,["T","B",2,2,"CyrillicOld","CyrillicOld","CyrillicOld.ttf","*",0,0,0,"-","-"]
/*6*/,["T","N",2,2,"DS Yermak_D","DSYermak_D","DS Yermak_D (2).ttf","*",0,0,0,"-","-"]
/*7*/,["T","N",2,2,"DSCyrillic","DSCyrillic","DSCyrillic (2).ttf","*",0,0,0,"-","-"]
/*8*/,["T","N",2,2,"GrkM","GrkM","GrkM.ttf","*",0,0,0,"-","-"]
/*9*/,["T","N",2,2,"GrkRus","GrkRusMT","GrkRus.ttf","*",0,0,0,"-","-"]
/*10*/,["T","N",2,2,"Hebrew","Hebrew","Hebrew (2).ttf","*",0,0,0,"-","-"]
/*11*/,["T","N",2,2,"Izhitsa","Izhitsa","Izhitsa.ttf","*",0,0,0,"-","-"]
/*12*/,["T","N",2,2,"OLBGRK","OLBGRK","OLBGRK.ttf","*",0,0,0,"-","-"]
/*13*/,["T","N",2,2,"OLBHEB","OLBHEB","OLBHEB.ttf","*",0,0,0,"-","-"]
/*14*/,["T","N",3,2,"Orthodox","Orthodox","Orthodox.ttf","*",0,0,0,"-","-"]
/*15*/,["T","N",3,2,"Orthodox.tt eRoos","Orthodox.tt-eRoos","OrteROOS.ttf","*",0,0,0,"-","-"]
/*16*/,["T","I",3,2,"Orthodox.tt eRoos","Orthodox.tt-eRoos-SpacedOut","OrtsROOS.ttf","*",0,0,0,"-","-"]
/*17*/,["T","N",3,2,"Orthodox.tt ieERoos","Orthodox.tt-ieERoos","OrieROOS.ttf","*",0,0,0,"-","-"]
/*18*/,["T","I",3,2,"Orthodox.tt ieERoos","Orthodox.tt-ieERoos-SpacedOut","OrisROOS.ttf","*",0,0,0,"-","-"]
/*19*/,["T","N",3,2,"Orthodox.tt ieUcs8","Orthodox.tt-ieUcs8","OriUCS8.ttf","*",0,0,0,"-","-"]
/*20*/,["T","I",3,2,"Orthodox.tt ieUcs8","Orthodox.tt-ieUcs8-SpacedOut","OriUCS8s.ttf","*",0,0,0,"-","-"]
/*21*/,["T","N",3,2,"Orthodox.tt ieUcs8 Caps","Orthodox.tt-ieUcs8-Caps","OriUCS8c.ttf","*",0,0,0,"-","-"]
/*22*/,["T","I",3,2,"Orthodox.tt ieUcs8 Caps","Orthodox.tt-ieUcs8-Caps-SpacedOut","OriUCScs.ttf","*",0,0,0,"-","-"]
/*23*/,["T","N",3,2,"Orthodox.tt ieUcs8 Drop Caps","Orthodox.tt-ieUcs8-Drop-Caps","OriUCS8d.ttf","*",0,0,0,"-","-"]
/*24*/,["T","N",3,2,"Orthodox.tt Ucs8","Orthodox.tt-Ucs8","OrtUCS8.ttf","*",0,0,0,"-","-"]
/*25*/,["T","I",3,2,"Orthodox.tt Ucs8","Orthodox.tt-Ucs8-SpacedOut","OrtUCS8s.ttf","*",0,0,0,"-","-"]
/*26*/,["T","N",3,2,"Orthodox.tt Ucs8 Caps","Orthodox.tt-Ucs8-Caps","OrtUCS8c.ttf","*",0,0,0,"-","-"]
/*27*/,["T","I",3,2,"Orthodox.tt Ucs8 Caps","Orthodox.tt-Ucs8-Caps-SpacedOut","OrtUCScs.ttf","*",0,0,0,"-","-"]
/*28*/,["T","N",3,2,"Orthodox.tt Ucs8 Caps tight","Orthodox.tt-Ucs8-Caps-tight","OrtUCSct.ttf","*",0,0,0,"-","-"]
/*29*/,["T","N",3,2,"Orthodox.tt Ucs8 Drop Caps","Orthodox.tt-Ucs8-Drop-Caps","OrtUCS8d.ttf","*",0,0,0,"-","-"]
/*30*/,["T","N",3,2,"Orthodox.tt Ucs8 tight","Orthodox.tt-Ucs8-tight","OrtUCS8t.ttf","*",0,0,0,"-","-"]
/*31*/,["T","N",3,2,"OrthodoxDigits","OrthodoxDigits","Ort_dig.ttf","*",0,0,0,"-","-"]
/*32*/,["T","N",3,2,"OrthodoxDigitsLoose","OrthodoxDigitsLoose","Ort_Ldig.ttf","*",0,0,0,"-","-"]
/*33*/,["T","N",3,2,"OrthodoxLoose","OrthodoxLoose","OrtLoose.ttf","*",0,0,0,"-","-"]
/*34*/,["T","N",3,2,"OrthodoxOrnament","OrthodoxOrnament","Ort_orn.ttf","*",0,0,0,"-","-"]
/*35*/,["T","N",2,2,"SBgr","SBgr","SBgr.ttf","*",0,0,0,"-","-"]
/*36*/,["T","N",2,2,"SBibFren","SBibFren","SBibFren.ttf","*",0,0,0,"-","-"]
/*37*/,["T","N",2,2,"SBibGer","SBibGer","SBibGer.ttf","*",0,0,0,"-","-"]
/*38*/,["T","N",2,2,"SBibGree","SBibGree","SBibGree.ttf","*",0,0,0,"-","-"]
/*39*/,["T","N",2,2,"SBibLat","SBibLat","SBibLat.ttf","*",0,0,0,"-","-"]
/*40*/,["T","N",2,2,"SBibRus","SBibRus","SBibRus.ttf","*",0,0,0,"-","-"]
/*41*/,["T","N",2,2,"SBibSlav","SBibSlav","SBibSlav (2).ttf","*",0,0,0,"-","-"]
/*42*/,["T","N",2,2,"SBSlav","SBSlav","SBSlav.ttf","*",0,0,0,"-","-"]
/*43*/,["T","N",2,2,"Slavanskay","Slavanskay","Slavanskay.ttf","*",0,0,0,"-","-"]
/*44*/,["T","N",2,2,"Slavjanic","Slavjanic","Slavjanic (2).ttf","*",0,0,0,"-","-"]
/*45*/,["T","N",2,2,"Ukrainian?Izhitsa","UkrainianIzhitsa","Ukrainian_Izhitsa.ttf","*",1,0,0,"-","-"]
/*46*/,["T","N",4,3,"Alexandra Script","AlexandraScript","Alexandra Script.ttf","*",0,0,0,"-","-"]
/*47*/,["T","N",4,3,"Allegretto Script One","AllegrettoScriptOne","Allegretto Script One.ttf","*",0,0,0,"-","-"]
/*48*/,["T","N",4,3,"Allegretto Script Two","AllegrettoScriptTwo","Allegretto Script Two.ttf","*",0,0,0,"-","-"]
/*49*/,["T","N",4,3,"Andantino script","Andantinoscript","Andantino script.ttf","*",0,0,0,"-","-"]
/*50*/,["T","N",4,3,"Annabelle","Annabelle","Annabelle.ttf","*",0,0,0,"-","-"]
/*51*/,["T","N",4,3,"Aquarelle","Aquarelle","Aquarelle.ttf","*",0,0,0,"-","-"]
/*52*/,["T","N",4,3,"Ariston","Ariston-Normal","Ariston Normal.ttf","*",0,0,0,"-","-"]
/*53*/,["T","N",4,3,"ArtScript","ArtScript","ArtScript.ttf","*",0,0,0,"-","-"]
/*54*/,["T","N",5,3,"Bickham Script One","BickhamScriptOne","Bickham Script One.ttf","*",0,0,0,"-","-"]
/*55*/,["T","N",5,3,"Bickham Script Three","BickhamScriptThree","Bickham Script Three.ttf","*",0,0,0,"-","-"]
/*56*/,["T","N",5,3,"Bickham Script Two","BickhamScriptTwo","Bickham Script Two.ttf","*",0,0,0,"-","-"]
/*57*/,["T","N",4,3,"Calligraph","Calligraph-Medium","Calligraph  Medium.ttf","*",0,0,0,"-","-"]
/*58*/,["T","N",4,3,"Calligrapher","Calligrapher","Calligrapher.ttf","*",0,0,0,"-","-"]
/*59*/,["T","N",4,3,"Cansellarist","Cansellarist","Cansellarist .ttf","*",0,0,0,"-","-"]
/*60*/,["T","N",4,3,"Cassandra","Cassandra","Cassandra.ttf","*",0,0,0,"-","-"]
/*61*/,["T","N",4,3,"Champagne Cyrillic","ChampagneCyrillic","Champagne Cyrillic.ttf","*",0,0,0,"-","-"]
/*62*/,["T","N",4,3,"Classica One","ClassicaOne","Classica One.ttf","*",0,0,0,"-","-"]
/*63*/,["T","N",4,3,"Classica Two","ClassicaTwo","Classica Two.ttf","*",0,0,0,"-","-"]
/*64*/,["T","N",4,3,"Copyist","Copyist","Copyist Thin.ttf","*",0,0,0,"-","-"]
/*65*/,["T","N",4,3,"CyrillicRibbon","CyrillicRibbon","CyrillicRibbon (2).ttf","*",0,0,0,"-","-"]
/*66*/,["T","N",6,3,"Decor","Decor","Decor.ttf","*",0,0,0,"-","-"]
/*67*/,["T","I",6,3,"Decor","Decor-Italic","Decor Italic.ttf","*",0,0,0,"-","-"]
/*68*/,["T","B",6,3,"Decor","Decor-Bold","Decor Bold.ttf","*",0,0,0,"-","-"]
/*69*/,["T","N",6,3,"DecorCTT","DecorCTT","DecorCTT (2).ttf","*",0,0,0,"-","-"]
/*70*/,["T","N",4,3,"English Script","EnglishScript","English Script.ttf","*",0,0,0,"-","-"]
/*71*/,["T","N",7,3,"Esenin script One","EseninscriptOne","Esenin script One.ttf","*",0,0,0,"-","-"]
/*72*/,["T","N",7,3,"Esenin script Two","EseninscriptTwo","Esenin script Two.ttf","*",0,0,0,"-","-"]
/*73*/,["T","N",4,3,"Gloria script","Gloriascript","Gloria script.ttf","*",0,0,0,"-","-"]
/*74*/,["T","N",4,3,"Heather Script One","HeatherScriptOne","Heather Script One.ttf","*",0,0,0,"-","-"]
/*75*/,["T","N",4,3,"Heather Script Two","HeatherScriptTwo","Heather Script Two.ttf","*",0,0,0,"-","-"]
/*76*/,["T","N",4,3,"Hogarth script","Hogarthscript","Hogarth script.ttf","*",0,0,0,"-","-"]
/*77*/,["T","N",4,3,"KB ChopinScript","KBChopinScript","KB ChopinScript.ttf","*",0,0,0,"-","-"]
/*78*/,["T","N",4,3,"Keetano Katakana","KeetanoKatakana-Regular","KeetanoKatakana Regular.ttf","*",0,0,0,"-","-"]
/*79*/,["T","N",4,3,"Koala Cyr","KoalaCyr","Koala Cyr.ttf","*",0,0,0,"-","-"]
/*80*/,["T","N",4,3,"Majestic","Majestic-","Majestic.ttf","*",0,0,0,"-","-"]
/*81*/,["T","N",4,3,"Majestic X","MajesticX","Majestic X.ttf","*",0,0,0,"-","-"]
/*82*/,["T","N",4,3,"Margarita script","Margaritascript","Margarita script.ttf","*",0,0,0,"-","-"]
/*83*/,["T","N",4,3,"Markiz de Sad script","MarkizdeSadscript","Markiz de Sad script.ttf","*",0,0,0,"-","-"]
/*84*/,["T","N",4,3,"Matilda","Matilda","Matilda.ttf","*",0,0,0,"-","-"]
/*85*/,["T","N",4,3,"Menuet script","Menuetscript","Menuet script.ttf","*",0,0,0,"-","-"]
/*86*/,["T","I",4,3,"Monotype Corsiva","MonotypeCorsiva","Monotype Corsiva.ttf","*",0,0,0,"-","-"]
/*87*/,["T","N",4,3,"OdessaScriptFWF","OdessaScriptFWF","OdessaScriptFWF Regular.ttf","*",0,0,0,"-","-"]
/*88*/,["T","N",4,3,"Ogilvie Cyr","Ogilvie Cyr","Ogilvie Cyr.ttf","*",0,0,0,"-","-"]
/*89*/,["T","N",4,3,"Orpheus","Orpheus","Orpheus.ttf","*",0,0,0,"-","-"]
/*90*/,["T","I",4,3,"Ouverture script","Ouverturescript","Ouverture script.ttf","*",0,0,0,"-","-"]
/*91*/,["T","N",4,3,"Painter","Painter","Painter.ttf","*",0,0,0,"-","-"]
/*92*/,["T","N",4,3,"Palette Cyr","PaletteCyr","Palette Cyr.ttf","*",0,0,0,"-","-"]
/*93*/,["T","N",4,3,"Park Avenue","ParkAvenueNormal","Park Avenue Normal.ttf","*",0,0,0,"-","-"]
/*94*/,["T","N",4,3,"ParkAvenue","ParkAvenue","ParkAvenue.ttf","*",0,0,0,"-","-"]
/*95*/,["T","N",4,3,"PresentScript","PresentScript_cyr","PresentScript Cyrillic.ttf","*",0,0,0,"-","-"]
/*96*/,["T","N",4,3,"Romantica script","Romanticascript","Romantica script.ttf","*",0,0,0,"-","-"]
/*97*/,["T","N",4,3,"Rosamunda One","RosamundaOne-Normal","Rosamunda One Normal.ttf","*",0,0,0,"-","-"]
/*98*/,["T","N",4,3,"Rosamunda Two","RosamundaTwo","Rosamunda Two.ttf","*",0,0,0,"-","-"]
/*99*/,["T","N",4,3,"Rubius","Rubius","Rubius.ttf","*",0,0,0,"-","-"]
/*100*/,["T","N",4,3,"Scriptorama","Scriptorama","Scriptorama.ttf","*",0,0,0,"-","-"]
/*101*/,["T","N",4,3,"Second Road","Second-Road","Second Road.ttf","*",0,0,0,"-","-"]
/*102*/,["T","N",4,3,"Still Time Cyr","StillTimeCyr","Still Time Cyr.ttf","*",0,0,0,"-","-"]
/*103*/,["T","I",4,3,"Torhok","TorhokItalic","Torhok Italic.ttf","*",0,0,0,"-","-"]
/*104*/,["T","N",4,3,"Uk_Decor","Uk_Decor","Uk_Decor.ttf","*",0,0,0,"-","-"]
/*105*/,["T","N",4,3,"Vera Crouz","VeraCrouz","Vera Crouz.ttf","*",0,0,0,"-","-"]
/*106*/,["T","N",4,3,"VivaldiD","VivaldiD","VivaldiD.ttf","*",0,0,0,"-","-"]
/*107*/,["T","I",4,3,"Zapf Chancery","ZapfChancer","Zapf Chancery Italic_001.007.ttf","*",0,0,0,"-","-"]
/*108*/,["T","I",4,3,"Zapf Russ","ZapfRussItalic","Zapf Russ Italic.ttf","*",0,0,0,"-","-"]
/*109*/,["T","I",4,3,"ZapfChancery","ZapfChancery_cyr","ZapfChancery Cyrillic Italic.ttf","*",0,0,0,"-","-"]
/*110*/,["T","N",4,3,"Zeferino One","ZeferinoOne","Zeferino One.ttf","*",0,0,0,"-","-"]
/*111*/,["T","N",4,3,"Zeferino Two","ZeferinoTwo","Zeferino Two.ttf","*",0,0,0,"-","-"]
/*112*/,["T","I",4,3,"ZurichCalligraphic","ZurichCalligraphicItalic","ZurichCalligraphic Italic.ttf","*",0,0,0,"-","-"]
/*113*/,["T","N",8,4,"Arbat","Arbat","Arbat.ttf","*",0,0,0,"-","-"]
/*114*/,["T","B",9,4,"BetinaScript","BetinaScriptBold","BetinaScript Bold.ttf","*",0,0,0,"-","-"]
/*115*/,["T","N",9,4,"BetinaScriptC","BetinaScriptC","BetinaScriptC.ttf","*",0,0,0,"-","-"]
/*116*/,["T","N",9,4,"BetinaScriptCTT","BetinaScriptCTT-Regular","BetinaScriptCTT.ttf","*",0,0,0,"-","-"]
/*117*/,["T","B",9,4,"BetinaScriptCTT","BetinaScriptCTT-Bold","BetinaScriptCTT Bold.ttf","*",0,0,0,"-","-"]
/*118*/,["T","N",9,4,"BetinaScriptExtraCTT","BetinaScriptExtraCTT-Regular","BetinaScriptExtraCTT.ttf","*",0,0,0,"-","-"]
/*119*/,["T","N",8,4,"BirchCTT","BirchCTT","BirchCTT.ttf","*",0,0,0,"-","-"]
/*120*/,["T","N",8,4,"Bolid","Bolid","Bolid.ttf","*",0,0,0,"-","-"]
/*121*/,["T","N",8,4,"Brody","Brody","Brody.ttf","*",0,0,0,"-","-"]
/*122*/,["O","N",8,4,"Caflisch Script Pro Regular","CaflischScriptPro-Regular","CaflischScriptPro-Regular.otf","*",0,0,0,"-","-"]
/*123*/,["T","N",10,4,"Comic Sans MS","ComicSansMS","Comic Sans MS.ttf","*",0,0,0,"-","-"]
/*124*/,["T","B",10,4,"Comic Sans MS","ComicSansMS-Bold","Comic Sans MS Bold.ttf","*",0,0,0,"-","-"]
/*125*/,["T","I",8,4,"Coronet","Coronet","Coronet.ttf","*",0,0,0,"-","-"]
/*126*/,["T","N",8,4,"Corrida","CorridaCyrillic","Corrida Cyrillic.ttf","*",0,0,0,"-","-"]
/*127*/,["T","B",8,4,"Corrida","Corrida-Bold","Corrida Bold.ttf","*",0,0,0,"-","-"]
/*128*/,["T","N",8,4,"CorridaC","CorridaC","CorridaC.ttf","*",0,0,0,"-","-"]
/*129*/,["T","N",8,4,"CyrillicBrush","CyrillicBrushMedium","CyrillicBrush Medium.ttf","*",0,0,0,"-","-"]
/*130*/,["T","N",8,4,"Jikharev","Jikharev","Jikharev.ttf","*",0,0,0,"-","-"]
/*131*/,["T","N",8,4,"Kaliakra","Kaliakra","Kaliakra.ttf","*",0,0,0,"-","-"]
/*132*/,["T","I",8,4,"KursivC","KursivC","KursivC (2).ttf","*",0,0,0,"-","-"]
/*133*/,["T","N",8,4,"Lazy Crazy","LazyCrazy","Lazy Crazy.ttf","*",0,0,0,"-","-"]
/*134*/,["T","N",8,4,"LC Chalk","LCChalk","LC Chalk.ttf","*",0,0,0,"-","-"]
/*135*/,["T","N",8,4,"Mistral","Mistral","Mistral.ttf","*",0,0,0,"-","-"]
/*136*/,["T","B",8,4,"Nadejda","NadejdaBold","Nadejda  Bold.ttf","*",0,0,0,"-","-"]
/*137*/,["T","N",8,4,"NfS MW","NfSMW","NfS MW.ttf","*",0,0,0,"-","-"]
/*138*/,["T","N",8,4,"Old Comedy","OldComedy","Old Comedy.ttf","*",0,0,0,"-","-"]
/*139*/,["T","N",8,4,"Oskord","Oskord","Oskord.ttf","*",0,0,0,"-","-"]
/*140*/,["T","N",8,4,"Parsek","Parsek","Parsek.ttf","*",0,0,0,"-","-"]
/*141*/,["T","N",8,4,"Pushkin","Pushkin","Pushkin.ttf","*",0,0,0,"-","-"]
/*142*/,["T","N",8,4,"Scrawl","Scrawl","Scrawl.ttf","*",0,0,0,"-","-"]
/*143*/,["T","N",11,4,"Segoe Print","SegoePrint","Segoe Print.ttf","*",0,0,0,"-","-"]
/*144*/,["T","B",11,4,"Segoe Print","SegoePrint-Bold","Segoe Print Bold.ttf","*",0,0,0,"-","-"]
/*145*/,["T","N",11,4,"Segoe Script","SegoeScript","Segoe Script.ttf","*",0,0,0,"-","-"]
/*146*/,["T","B",11,4,"Segoe Script","SegoeScript-Bold","Segoe Script Bold.ttf","*",0,0,0,"-","-"]
/*147*/,["T","B",8,4,"Stylo","Stylo-Bold","Stylo Bold.ttf","*",0,0,0,"-","-"]
/*148*/,["T","N",8,4,"Tagir DP Normal","TagirDPNormal","Tagir DP Normal.ttf","*",0,0,0,"-","-"]
/*149*/,["T","N",8,4,"TagirCTT","TagirCTT","TagirCTT.ttf","*",0,0,0,"-","-"]
/*150*/,["T","N",8,4,"UkrainianBrushScript","UkrainianBrushScript","UkrainianBrushScript.ttf","*",0,0,0,"-","-"]
/*151*/,["T","N",8,4,"Ænigma Scrawl (BRK)","AEnigmaScrawl(BRK)","Enigma Scrawl (BRK).ttf","*",0,0,0,"-","-"]
/*152*/,["T","N",12,5,"CyrillicGoth","CyrillicGoth","CyrillicGoth (2).ttf","*",0,0,0,"-","-"]
/*153*/,["T","N",12,5,"Deutsch Gothic","DeutschGothic","Deutsch Gothic.ttf","*",0,0,0,"-","-"]
/*154*/,["T","N",12,5,"Dr.Po GothicRu","Dr.PoGothicRu","Dr.Po GothicRu.ttf","*",0,0,0,"-","-"]
/*155*/,["T","N",12,5,"DrPoDecorRu","DrPoDecorRu","DrPoDecorRu (2).ttf","*",0,0,0,"-","-"]
/*156*/,["T","N",12,5,"Encient German Gothic","Encient German Gothic","Encient German Gothic (2).ttf","*",0,0,0,"-","-"]
/*157*/,["T","N",12,5,"GothicE","GothicE","GothicE.ttf","*",0,0,0,"-","-"]
/*158*/,["T","N",12,5,"GothicI","GothicI","GothicI.ttf","*",0,0,0,"-","-"]
/*159*/,["T","B",12,5,"GothicRus","PaladinPCRusMedium","GothicRus Bold.ttf","*",0,0,0,"-","-"]
/*160*/,["T","N",12,5,"GothicRus Condenced","GothicRusMedium","GothicRus Condenced.ttf","*",0,0,0,"-","-"]
/*161*/,["T","N",12,5,"PaladinPCRus","PaladinPCRusMedium","PaladinPCRus Medium (2).ttf","*",0,0,0,"-","-"]
/*162*/,["T","N",12,5,"Verona Gothic Flourishe","VeronaGothicFlourishe","Verona Gothic Flourishe.ttf","*",0,0,0,"-","-"]
/*163*/,["T","N",13,6,"911 Porscha","911Porscha","911 Porscha.ttf","*",0,0,0,"-","-"]
/*164*/,["T","N",14,6,"a_Algerius","AAlgerius","a_Algerius.ttf","*",0,0,0,"-","-"]
/*165*/,["T","N",14,6,"a_AlgeriusBlw","a_AlgeriusBlw","a_AlgeriusBlw.ttf","*",0,0,0,"-","-"]
/*166*/,["T","N",14,6,"a_AlgeriusBrk","a_AlgeriusBrk","a_AlgeriusBrk.ttf","*",0,0,0,"-","-"]
/*167*/,["T","N",14,6,"a_AlgeriusCaps","AAlgeriusCaps","a_AlgeriusCaps.ttf","*",0,0,0,"-","-"]
/*168*/,["T","N",14,6,"a_AlgeriusCapsNr","AAlgeriusCapsNr","a_AlgeriusCapsNr.ttf","*",0,0,0,"-","-"]
/*169*/,["T","N",14,6,"a_AlgeriusCmDc1Cmb","a_AlgeriusCmDc1Cmb","a_AlgeriusCmDc1Cmb.ttf","*",0,0,0,"-","-"]
/*170*/,["T","N",14,6,"a_AlgeriusCmDc2Cmb","a_AlgeriusCmDc2Cmb","a_AlgeriusCmDc2Cmb.ttf","*",0,0,0,"-","-"]
/*171*/,["T","N",14,6,"a_AlgeriusCmDgStr","AAlgeriusCmDgStr","a_AlgeriusCmDgStr.ttf","*",0,0,0,"-","-"]
/*172*/,["T","N",14,6,"a_AlgeriusCmFtz1","AAlgeriusCmFtz1","a_AlgeriusCmFtz1.ttf","*",0,0,0,"-","-"]
/*173*/,["T","N",14,6,"a_AlgeriusNr","AAlgeriusNr","a_AlgeriusNr.ttf","*",0,0,0,"-","-"]
/*174*/,["T","N",14,6,"a_AlgeriusNrCm","AAlgeriusNrCm","a_AlgeriusNrCm.ttf","*",0,0,0,"-","-"]
/*175*/,["T","N",14,6,"a_AlgeriusNrCmDn","AAlgeriusNrCmDn","a_AlgeriusNrCmDn.ttf","*",0,0,0,"-","-"]
/*176*/,["T","N",14,6,"a_AlgeriusNrCmUp","AAlgeriusNrCmUp","a_AlgeriusNrCmUp.ttf","*",0,0,0,"-","-"]
/*177*/,["T","N",14,6,"a_AlgeriusNrDcCm","AAlgeriusNrDcCm","a_AlgeriusNrDcCm.ttf","*",0,0,0,"-","-"]
/*178*/,["T","N",14,6,"a_AlgeriusOtl","AAlgeriusOtl","a_AlgeriusOtl.ttf","*",0,0,0,"-","-"]
/*179*/,["T","N",14,6,"a_AlgeriusRough","a_AlgeriusRough","a_AlgeriusRough.ttf","*",0,0,0,"-","-"]
/*180*/,["T","N",13,6,"China","China","China.ttf","*",0,0,0,"-","-"]
/*181*/,["T","N",15,6,"Decoder","Decoder","Decoder.ttf","*",0,0,0,"-","-"]
/*182*/,["T","N",15,6,"Digital dream","Digitaldream","Digital dream.ttf","*",0,0,0,"-","-"]
/*183*/,["T","N",15,6,"Digital dream Skew Narrow","DigitaldreamSkewNarrow","Digital dream Skew Narrow.ttf","*",0,0,0,"-","-"]
/*184*/,["T","N",15,6,"Digital Readout","DigitalReadout","Digital Readout.ttf","*",0,0,0,"-","-"]
/*185*/,["T","N",15,6,"Digital Readout Condensed","DigitalReadoutCondensed","Digital Readout Condensed.ttf","*",0,0,0,"-","-"]
/*186*/,["T","N",15,6,"Digital Readout CondUpright","DigitalReadoutCondUpright","Digital Readout CondUpright.ttf","*",0,0,0,"-","-"]
/*187*/,["T","N",15,6,"Digital Readout Expanded","DigitalReadoutExpanded","Digital Readout Expanded.ttf","*",0,0,0,"-","-"]
/*188*/,["T","N",15,6,"Digital Readout ExpUpright","DigitalReadoutExpUpright","Digital Readout ExpUpright.ttf","*",0,0,0,"-","-"]
/*189*/,["T","N",15,6,"Digital Readout Thick","DigitalReadoutThick","Digital Readout Thick.ttf","*",0,0,0,"-","-"]
/*190*/,["T","N",15,6,"Digital Readout Thick Upright","DigitalReadoutThickUpright","Digital Readout Thick Upright.ttf","*",0,0,0,"-","-"]
/*191*/,["T","N",15,6,"Digital Readout Upright","DigitalReadoutUpright","Digital Readout Upright.ttf","*",0,0,0,"-","-"]
/*192*/,["T","N",15,6,"Digital SF","DigitalSF","Digital SF.ttf","*",0,0,0,"-","-"]
/*193*/,["T","N",15,6,"Digital-7","Digital-7","Digital-7.ttf","*",0,0,0,"-","-"]
/*194*/,["T","I",15,6,"Digital-7 Italic","Digital-7Italic","Digital-7 Italic.ttf","*",0,0,0,"-","-"]
/*195*/,["T","N",15,6,"Digital-7 Mono","Digital-7Mono","Digital-7 Mono.ttf","*",0,0,0,"-","-"]
/*196*/,["T","N",15,6,"Digital2","Digital2-Medium","Digital2 Medium.ttf","*",0,0,0,"-","-"]
/*197*/,["T","N",16,6,"DotMatrix","DotMatrix Regular","DotMatrix Regular.ttf","*",0,0,0,"-","-"]
/*198*/,["T","N",13,6,"Drifter","DrifterFive","Drifter.TTF","*",0,0,0,"-","-"]
/*199*/,["T","N",16,6,"Epson1","Epson1","Epson1.ttf","*",0,0,0,"-","-"]
/*200*/,["T","N",16,6,"Epson2","Epson2","Epson2.ttf","*",0,0,0,"-","-"]
/*201*/,["T","N",13,6,"Fabulous","New","Fabulous.ttf","*",0,0,0,"-","-"]
/*202*/,["T","N",13,6,"Freon","Freon","Freon.ttf","*",0,0,0,"-","-"]
/*203*/,["T","N",13,6,"hooge 05_53","Hooge0553","hooge 05_53.ttf","*",0,0,0,"-","-"]
/*204*/,["T","N",13,6,"hooge 05_54","Hooge0554","hooge 05_54.ttf","*",0,0,0,"-","-"]
/*205*/,["T","N",13,6,"hooge 05_55","Hooge0555","hooge 05_55.ttf","*",0,0,0,"-","-"]
/*206*/,["T","N",16,6,"J_EKR","J_EKR","J_EKR.ttf","*",0,0,0,"-","-"]
/*207*/,["T","N",16,6,"J_EKR_B","J_EKR_B","J_EKR_B.ttf","*",0,0,0,"-","-"]
/*208*/,["T","N",16,6,"J_EKR_B_N","J_EKR_B_N","J_EKR_B_N.ttf","*",0,0,0,"-","-"]
/*209*/,["T","N",16,6,"J_NAKL_","J_NAKL_","J_NAKL_.ttf","*",0,0,0,"-","-"]
/*210*/,["T","N",13,6,"Sea-Dog","Sea-Dog","Sea-Dog.ttf","*",0,0,0,"-","-"]
/*211*/,["T","N",17,7,"a_OldTyperCmDcFnt1","a_OldTypingCmDcFnt1","a_OldTypingCmDcFnt1.ttf","*",0,0,0,"-","-"]
/*212*/,["T","B",17,7,"a_UncleyTitulB&W","a_UncleyTitulB&W-Bold","a_UncleyTitulB&W Bold.ttf","*",0,0,0,"-","-"]
/*213*/,["T","N",17,7,"Acadian","AcadianCyr","Acadian Cyr.ttf","*",0,0,0,"-","-"]
/*214*/,["T","N",17,7,"Airport Cyr","AirportCyr","Airport Cyr.ttf","*",0,0,0,"-","-"]
/*215*/,["T","N",17,7,"Amadeus","Amadeus","Amadeus.ttf","*",0,0,0,"-","-"]
/*216*/,["T","N",18,7,"Art Nouveau-Bistro","ArtNouveau-Bistro","Art Nouveau-Bistro.ttf","*",0,0,0,"-","-"]
/*217*/,["T","N",18,7,"Art Nouveau-Cafe","ArtNouveau-Cafe","Art Nouveau-Cafe.ttf","*",0,0,0,"-","-"]
/*218*/,["T","N",17,7,"Art-Metropol","Art-Metropol","Art-Metropol.ttf","*",0,0,0,"-","-"]
/*219*/,["T","N",18,7,"Art-Nouveau 1895","Art-Nouveau1895","Art-Nouveau 1895.ttf","*",0,0,0,"-","-"]
/*220*/,["T","N",18,7,"Art-Nouveau 1895-Contour","Art-Nouveau1895-Contour","Art-Nouveau 1895-Contour.ttf","*",0,0,0,"-","-"]
/*221*/,["T","N",18,7,"Art-Nouveau 1900","Art-Nouveau1900","Art-Nouveau 1900.ttf","*",0,0,0,"-","-"]
/*222*/,["T","N",18,7,"Art-Nouveau 1910","Art-Nouveau1910","Art-Nouveau 1910.ttf","*",0,0,0,"-","-"]
/*223*/,["T","N",17,7,"Astron","AstronCyrillic","Astron Cyrillic.ttf","*",0,0,0,"-","-"]
/*224*/,["T","N",17,7,"Beast Impacted","BeastImpacted","Beast Impacted Regular.ttf","*",0,0,0,"-","-"]
/*225*/,["T","N",17,7,"Ben Krush","Ben Krush","Ben Krush.ttf","*",0,0,0,"-","-"]
/*226*/,["T","N",17,7,"Benny Blanco","BennyBlanco","Benny Blanco.ttf","*",0,0,0,"-","-"]
/*227*/,["T","N",17,7,"Betsy Flanagan","BetsyFlanagan","Betsy Flanagan.ttf","*",0,0,0,"-","-"]
/*228*/,["T","N",17,7,"Blaze","Blaze","Blaze.ttf","*",0,0,0,"-","-"]
/*229*/,["T","N",17,7,"Blood Cyrillic","Blood-Cyrillic","Blood Cyrillic.ttf","*",0,0,0,"-","-"]
/*230*/,["T","N",17,7,"Collins","Collins","Collins.ttf","*",0,0,0,"-","-"]
/*231*/,["T","N",17,7,"DreamScar","DreamScar","DreamScar.ttf","*",0,0,0,"-","-"]
/*232*/,["T","N",17,7,"DS Arabic","DSArabic","DS Arabic (2).ttf","*",0,0,0,"-","-"]
/*233*/,["T","N",17,7,"DS Brushes","DSBrushes-Normal","DS Brushes Normal.ttf","*",0,0,0,"-","-"]
/*234*/,["T","N",17,7,"FrankC","PS=FrankC","FrankC.ttf","*",0,0,0,"-","-"]
/*235*/,["T","B",17,7,"Frant","Frant-Bold","Frant Bold.ttf","*",0,0,0,"-","-"]
/*236*/,["T","N",17,7,"Grunge","Grunge","Grunge.ttf","*",0,0,0,"-","-"]
/*237*/,["T","N",17,7,"Hrom","Hrom","Hrom.ttf","*",0,0,0,"-","-"]
/*238*/,["T","N",17,7,"Mars Police","MarsPolice","Mars Police.ttf","*",0,0,0,"-","-"]
/*239*/,["T","N",17,7,"Marta Decor Two","MartaDecorTwo","Marta Decor Two.ttf","*",0,0,0,"-","-"]
/*240*/,["T","N",17,7,"Matreshka","Matreshka","Matreshka.ttf","*",0,0,0,"-","-"]
/*241*/,["T","N",17,7,"Matricha","Matricha","Matricha.ttf","*",0,0,0,"-","-"]
/*242*/,["T","N",17,7,"Matrix_vs_Miltown","Matrix_vs_Miltown","Matrix_vs_Miltown.ttf","*",0,0,0,"-","-"]
/*243*/,["T","N",17,7,"Monte-Carlo","Monte-Carlo","Monte-Carlo.ttf","*",0,0,0,"-","-"]
/*244*/,["T","N",17,7,"Moonchild","MoonchildNormal","Moonchild Normal.ttf","*",0,0,0,"-","-"]
/*245*/,["T","N",17,7,"Moonlight","Moonlight","Moonlight.ttf","*",0,0,0,"-","-"]
/*246*/,["T","N",17,7,"Moonstone Stars","MoonstoneStars","Moonstone Stars.ttf","*",0,0,0,"-","-"]
/*247*/,["T","N",17,7,"Ocean","Ocean-Normal","Ocean Normal.ttf","*",0,0,0,"-","-"]
/*248*/,["T","N",17,7,"Postmodern Two","PostmodernTwo","Postmodern Two.ttf","*",0,0,0,"-","-"]
/*249*/,["T","N",17,7,"Skurri","Skurri","Skurri.ttf","*",0,0,0,"-","-"]
/*250*/,["T","N",17,7,"Viking Cyr","VikingCyr","Viking Cyr.ttf","*",0,0,0,"-","-"]
/*251*/,["T","I",17,7,"Viza","Viza","Viza.ttf","*",0,0,0,"-","-"]
/*252*/,["T","N",17,7,"Whirl Cyrillic","WhirlCyrillic","Whirl Cyrillic.ttf","*",0,0,0,"-","-"]
/*253*/,["T","N",17,7,"Xorx_Toothy Cyr","Xorx_ToothyCyr","Xorx_Toothy Cyr.ttf","*",0,0,0,"-","-"]
/*254*/,["T","N",17,7,"Xorx_windy Cyr","Xorx_windyCyr","Xorx_windy Cyr.ttf","*",0,0,0,"-","-"]
/*255*/,["T","N",17,7,"Zanesennyj","Zanesennyj","Zanesennyj.ttf","*",0,0,0,"-","-"]
/*256*/,["T","N",19,8,"Courier New","CourierNewPSMT","Courier New.ttf","*",0,0,0,"-","-"]
/*257*/,["T","I",19,8,"Courier New","CourierNewPS-ItalicMT","Courier New Italic.ttf","*",0,0,0,"-","-"]
/*258*/,["T","B",19,8,"Courier New","CourierNewPS-BoldMT","Courier New Bold.ttf","*",0,0,0,"-","-"]
/*259*/,["T","T",19,8,"Courier New","CourierNewPS-BoldItalicMT","Courier New Bold Italic.ttf","*",0,0,0,"-","-"]
/*260*/,["O","N",20,8,"Courier Std","CourierStd","CourierStd.otf","*",0,0,0,"-","-"]
/*261*/,["O","I",20,8,"Courier Std","CourierStd-Oblique","CourierStd-Oblique.otf","*",0,0,0,"-","-"]
/*262*/,["O","B",20,8,"Courier Std","CourierStd-Bold","CourierStd-Bold.otf","*",0,0,0,"-","-"]
/*263*/,["O","T",20,8,"Courier Std","CourierStd-BoldOblique","CourierStd-BoldOblique.otf","*",0,0,0,"-","-"]
/*264*/,["T","N",21,8,"DilleniaUPC","DilleniaUPC","DilleniaUPC.ttf","*",0,0,0,"-","-"]
/*265*/,["T","I",21,8,"DilleniaUPC","DilleniaUPCItalic","DilleniaUPC Italic.ttf","*",0,0,0,"-","-"]
/*266*/,["T","B",21,8,"DilleniaUPC","DilleniaUPCBold","DilleniaUPC Bold.ttf","*",0,0,0,"-","-"]
/*267*/,["T","T",21,8,"DilleniaUPC","DilleniaUPCBoldItalic","DilleniaUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*268*/,["T","N",22,8,"Ezra SIL","EzraSIL","Ezra SIL.ttf","*",0,0,0,"-","-"]
/*269*/,["T","N",22,8,"Ezra SIL SR","EzraSILSR","Ezra SIL SR.ttf","*",0,0,0,"-","-"]
/*270*/,["T","N",23,8,"Fixed Miriam Transparent","FixedMiriamTransparent","miriam fixed transp.ttf","*",0,0,0,"-","-"]
/*271*/,["T","N",23,8,"Miriam Fixed","MiriamFixed","Miriam Fixed.ttf","*",0,0,0,"-","-"]
/*272*/,["T","N",23,8,"Rod","Rod","Rod.ttf","*",0,0,0,"-","-"]
/*273*/,["T","N",23,8,"Rod Transparent","RodTransparent","Rod Transparent.ttf","*",0,0,0,"-","-"]
/*274*/,["T","B",24,9,"a_Albionic","AAlbionicBold","a_Albionic Bold.ttf","*",0,0,0,"-","-"]
/*275*/,["T","N",24,9,"a_AlbionicB&W","AAlbionicBW","a_AlbionicB&W.ttf","*",0,0,0,"-","-"]
/*276*/,["T","B",24,9,"a_AlbionicExp","AAlbionicExpBold","a_AlbionicExp Bold.ttf","*",0,0,0,"-","-"]
/*277*/,["T","B",24,9,"a_AlbionicNr","AAlbionicNrBold","a_AlbionicNr Bold.ttf","*",0,0,0,"-","-"]
/*278*/,["T","N",24,9,"a_AlbionicNrOtl","AAlbionicNrOtl","a_AlbionicNrOtl.ttf","*",0,0,0,"-","-"]
/*279*/,["T","N",24,9,"a_AlbionicTitulNrSh","AAlbionicTitulNrSh","a_AlbionicTitulNrSh.ttf","*",0,0,0,"-","-"]
/*280*/,["T","N",25,9,"Dungeon","Dungeon-Regular","Dungeon.ttf","*",0,0,0,"-","-"]
/*281*/,["T","N",26,9,"IrisUPC","IrisUPC","IrisUPC.ttf","*",0,0,0,"-","-"]
/*282*/,["T","I",26,9,"IrisUPC","IrisUPCItalic","IrisUPC Italic.ttf","*",0,0,0,"-","-"]
/*283*/,["T","B",26,9,"IrisUPC","IrisUPCBold","IrisUPC Bold.ttf","*",0,0,0,"-","-"]
/*284*/,["T","T",26,9,"IrisUPC","IrisUPCBoldItalic","IrisUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*285*/,["T","N",27,9,"JasmineUPC","JasmineUPC","JasmineUPC.ttf","*",0,0,0,"-","-"]
/*286*/,["T","I",27,9,"JasmineUPC","JasmineUPC-Italic","JasmineUPC Italic.ttf","*",0,0,0,"-","-"]
/*287*/,["T","B",27,9,"JasmineUPC","JasmineUPC-Bold","JasmineUPC Bold.ttf","*",0,0,0,"-","-"]
/*288*/,["T","T",27,9,"JasmineUPC","JasmineUPC-BoldItalic","JasmineUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*289*/,["O","N",28,9,"Lithos Pro Extra Light","LithosPro-ExtraLight","LithosPro-ExtraLight.otf","*",0,0,0,"-","-"]
/*290*/,["O","N",28,9,"Lithos Pro Light","LithosPro-Light","LithosPro-Light.otf","*",0,0,0,"-","-"]
/*291*/,["O","B",28,9,"Lithos Pro Light","LithosPro-Bold","LithosPro-Bold.otf","*",0,0,0,"-","-"]
/*292*/,["O","N",28,9,"Lithos Pro Regular","LithosPro-Regular","LithosPro-Regular.otf","*",0,0,0,"-","-"]
/*293*/,["O","B",28,9,"Lithos Pro Regular","LithosPro-Black","LithosPro-Black.otf","*",0,0,0,"-","-"]
/*294*/,["T","N",25,9,"Narkisim","Narkisim","Narkisim.ttf","*",0,0,0,"-","-"]
/*295*/,["T","N",29,10,"a_Alterna","AAlterna","a_Alterna.ttf","*",0,0,0,"-","-"]
/*296*/,["T","N",29,10,"a_AlternaNr","AAlternaNr","a_AlternaNr.ttf","*",0,0,0,"-","-"]
/*297*/,["T","N",29,10,"a_AlternaOtl","AAlternaOtl","a_AlternaOtl.ttf","*",0,0,0,"-","-"]
/*298*/,["T","B",29,10,"a_AlternaRg","a_AlternaRg","a_AlternaRg.ttf","*",0,0,0,"-","-"]
/*299*/,["T","N",29,10,"a_AlternaSh","AAlternaSh","a_AlternaSh.ttf","*",0,0,0,"-","-"]
/*300*/,["T","N",29,10,"a_AlternaTitul3D","AAlternaTitul3D","a_AlternaTitul3D.ttf","*",0,0,0,"-","-"]
/*301*/,["T","N",29,10,"a_AlternaTitulB&W","AAlternaTitulBW","a_AlternaTitulB&W.ttf","*",0,0,0,"-","-"]
/*302*/,["O","N",30,10,"Adobe Jenson Pro","AJensonPro-Regular","AJensonPro-Regular.otf","*",0,0,0,"-","-"]
/*303*/,["O","I",30,10,"Adobe Jenson Pro","AJensonPro-It","AJensonPro-It.otf","*",0,0,0,"-","-"]
/*304*/,["O","B",30,10,"Adobe Jenson Pro","AJensonPro-Bold","AJensonPro-Bold.otf","*",0,0,0,"-","-"]
/*305*/,["O","T",30,10,"Adobe Jenson Pro","AJensonPro-BoldIt","AJensonPro-BoldIt.otf","*",0,0,0,"-","-"]
/*306*/,["O","N",30,10,"Adobe Jenson Pro Lt","AJensonPro-Lt","AJensonPro-Lt.otf","*",0,0,0,"-","-"]
/*307*/,["O","I",30,10,"Adobe Jenson Pro Lt","AJensonPro-LtIt","AJensonPro-LtIt.otf","*",0,0,0,"-","-"]
/*308*/,["O","B",30,10,"Adobe Jenson Pro Lt","AJensonPro-Semibold","AJensonPro-Semibold.otf","*",0,0,0,"-","-"]
/*309*/,["O","T",30,10,"Adobe Jenson Pro Lt","AJensonPro-SemiboldIt","AJensonPro-SemiboldIt.otf","*",0,0,0,"-","-"]
/*310*/,["T","B",31,10,"Aharoni","AharoniBold","Aharoni Bold.ttf","*",0,0,0,"-","-"]
/*311*/,["T","N",32,10,"Andale Mono","AndaleMono","Andale Mono.ttf","*",0,0,0,"-","-"]
/*312*/,["T","N",33,10,"Arabic Transparent","ArabicTransparent","Arabic Transparent.ttf","*",0,0,0,"-","-"]
/*313*/,["T","B",33,10,"Arabic Transparent","ArabicTransparent-Bold","Arabic Transparent Bold.ttf","*",0,0,0,"-","-"]
/*314*/,["T","N",34,10,"Arial","ArialMT","Arial.ttf","*",0,0,0,"-","-"]
/*315*/,["T","I",34,10,"Arial","Arial-ItalicMT","Arial Italic.ttf","*",0,0,0,"-","-"]
/*316*/,["T","B",34,10,"Arial","Arial-BoldMT","Arial Bold.ttf","*",0,0,0,"-","-"]
/*317*/,["T","T",34,10,"Arial","Arial-BoldItalicMT","Arial Bold Italic.ttf","*",0,0,0,"-","-"]
/*318*/,["T","N",35,10,"Arial Alternative","ArialAlternative","Arial Alternative Regular.ttf","*",0,0,0,"-","-"]
/*319*/,["T","N",34,10,"Arial Black","Arial-Black","Arial Black.ttf","*",0,0,0,"-","-"]
/*320*/,["T","N",36,10,"Arial Narrow","ArialNarrow","Arial Narrow+.ttf","*",0,0,0,"-","-"]
/*321*/,["T","I",36,10,"Arial Narrow","ArialNarrow-Italic","Arial Narrow Italic.ttf","*",0,0,0,"-","-"]
/*322*/,["T","B",36,10,"Arial Narrow","ArialNarrow-Bold","Arial Narrow Bold.ttf","*",0,0,0,"-","-"]
/*323*/,["T","T",36,10,"Arial Narrow","ArialNarrow-BoldItalic","Arial Narrow Bold Italic+.ttf","*",0,0,0,"-","-"]
/*324*/,["O","N",37,10,"Bell Gothic Std Black","BellGothicStd-Black","BellGothicStd-Black.otf","*",0,0,0,"-","-"]
/*325*/,["O","N",37,10,"Bell Gothic Std Light","BellGothicStd-Light","BellGothicStd-Light.otf","*",0,0,0,"-","-"]
/*326*/,["O","B",37,10,"Bell Gothic Std Light","BellGothicStd-Bold","BellGothicStd-Bold.otf","*",0,0,0,"-","-"]
/*327*/,["T","N",38,10,"Browallia New","BrowalliaNew","Browallia New.ttf","*",0,0,0,"-","-"]
/*328*/,["T","I",38,10,"Browallia New","BrowalliaNew-Italic","Browallia New Italic.ttf","*",0,0,0,"-","-"]
/*329*/,["T","B",38,10,"Browallia New","BrowalliaNew-Bold","Browallia New Bold.ttf","*",0,0,0,"-","-"]
/*330*/,["T","T",38,10,"Browallia New","BrowalliaNew-BoldItalic","Browallia New Bold Italic.ttf","*",0,0,0,"-","-"]
/*331*/,["T","N",38,10,"BrowalliaUPC","BrowalliaUPC","BrowalliaUPC.ttf","*",0,0,0,"-","-"]
/*332*/,["T","I",38,10,"BrowalliaUPC","BrowalliaUPC-Italic","BrowalliaUPC  Italic.ttf","*",0,0,0,"-","-"]
/*333*/,["T","B",38,10,"BrowalliaUPC","BrowalliaUPC-Bold","BrowalliaUPC  Bold.ttf","*",0,0,0,"-","-"]
/*334*/,["T","T",38,10,"BrowalliaUPC","BrowalliaUPC-BoldItalic","BrowalliaUPC  Bold Italic.ttf","*",0,0,0,"-","-"]
/*335*/,["T","N",39,10,"Calibri","Calibri","Calibri.ttf","*",0,0,0,"-","-"]
/*336*/,["T","I",39,10,"Calibri","Calibri-Italic","Calibri Italic.ttf","*",0,0,0,"-","-"]
/*337*/,["T","B",39,10,"Calibri","Calibri-Bold","Calibri Bold.ttf","*",0,0,0,"-","-"]
/*338*/,["T","T",39,10,"Calibri","Calibri-BoldItalic","Calibri Bold Italic.ttf","*",0,0,0,"-","-"]
/*339*/,["T","N",40,10,"Cordia New","CordiaNew","Cordia New.ttf","*",0,0,0,"-","-"]
/*340*/,["T","I",40,10,"Cordia New","CordiaNew-Italic","Cordia New Italic.ttf","*",0,0,0,"-","-"]
/*341*/,["T","B",40,10,"Cordia New","CordiaNew-Bold","Cordia New Bold.ttf","*",0,0,0,"-","-"]
/*342*/,["T","T",40,10,"Cordia New","CordiaNew-BoldItalic","Cordia New Bold Italic.ttf","*",0,0,0,"-","-"]
/*343*/,["T","N",40,10,"CordiaUPC","CordiaUPC","CordiaUPC.ttf","*",0,0,0,"-","-"]
/*344*/,["T","I",40,10,"CordiaUPC","CordiaUPC-Italic","CordiaUPC  Italic.ttf","*",0,0,0,"-","-"]
/*345*/,["T","B",40,10,"CordiaUPC","CordiaUPC-Bold","CordiaUPC  Bold.ttf","*",0,0,0,"-","-"]
/*346*/,["T","T",40,10,"CordiaUPC","CordiaUPC-BoldItalic","CordiaUPC  Bold Italic.ttf","*",0,0,0,"-","-"]
/*347*/,["T","N",32,10,"Enigmatic Unicode","EnigmaticUnicode","EnigmaU_2.TTF","*",0,0,0,"-","-"]
/*348*/,["T","N",41,10,"Epsy Sans","EpsySans","Epsy Sans.ttf","*",0,0,0,"-","-"]
/*349*/,["T","N",42,10,"Franklin Gothic Medium","FranklinGothic-Medium","Franklin Gothic Medium.ttf","*",0,0,0,"-","-"]
/*350*/,["T","I",42,10,"Franklin Gothic Medium","FranklinGothic-MediumItalic","Franklin Gothic Medium Italic.ttf","*",0,0,0,"-","-"]
/*351*/,["T","N",32,10,"FreeSans","FreeSans","FreeSans.ttf","*",0,0,0,"-","-"]
/*352*/,["T","B",32,10,"FreeSans","FreeSansBold","FreeSansBold.ttf","*",0,0,0,"-","-"]
/*353*/,["T","N",43,10,"FreesiaUPC","FreesiaUPC","FreesiaUPC.ttf","*",0,0,0,"-","-"]
/*354*/,["T","I",43,10,"FreesiaUPC","FreesiaUPCItalic","FreesiaUPC Italic.ttf","*",0,0,0,"-","-"]
/*355*/,["T","B",43,10,"FreesiaUPC","FreesiaUPCBold","FreesiaUPC Bold.ttf","*",0,0,0,"-","-"]
/*356*/,["T","T",43,10,"FreesiaUPC","FreesiaUPCBoldItalic","FreesiaUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*357*/,["T","N",44,10,"Gill Sans MT Condensed","GillSansMT-Condensed","Gill Sans MT Condensed.ttf","*",0,0,0,"-","-"]
/*358*/,["T","N",45,10,"Haettenschweiler","Haettenschweiler","Haettenschweiler.ttf","*",0,0,0,"-","-"]
/*359*/,["1","N",46,10,"HS Grotesk","HSGrotesk","HSGRON__.pfm","*",0,0,0,"-","-"]
/*360*/,["1","B",46,10,"HS Grotesk","HSGrotesk-Bold","HSGROB__.pfm","*",0,0,0,"-","-"]
/*361*/,["T","N",45,10,"Impact","Impact","Impact.ttf","*",0,0,0,"-","-"]
/*362*/,["T","B",47,10,"Iskar","Iskar-Bold","Iskar Bold.ttf","*",0,0,0,"-","-"]
/*363*/,["T","N",32,10,"LCARS","LCARS","lcars.ttf","*",0,0,0,"-","-"]
/*364*/,["T","N",48,10,"Levenim MT","LevenimMT","Levenim MT.ttf","*",0,0,0,"-","-"]
/*365*/,["T","B",48,10,"Levenim MT","LevenimMTBold","Levenim MT Bold.ttf","*",0,0,0,"-","-"]
/*366*/,["T","N",49,10,"LilyUPC","LilyUPC","LilyUPC.ttf","*",0,0,0,"-","-"]
/*367*/,["T","I",49,10,"LilyUPC","LilyUPCItalic","LilyUPC Italic.ttf","*",0,0,0,"-","-"]
/*368*/,["T","B",49,10,"LilyUPC","LilyUPCBold","LilyUPC Bold.ttf","*",0,0,0,"-","-"]
/*369*/,["T","T",49,10,"LilyUPC","LilyUPCBoldItalic","LilyUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*370*/,["T","N",32,10,"Lingoes Unicode","LingoesUnicode","Lingoes Unicode.ttf","*",0,0,0,"-","-"]
/*371*/,["T","N",50,10,"Lucida Sans","LucidaSans","Lucida Sans Regular.ttf","*",0,0,0,"-","-"]
/*372*/,["T","I",50,10,"Lucida Sans","LucidaSans-Italic","Lucida Sans Italic.ttf","*",0,0,0,"-","-"]
/*373*/,["T","B",50,10,"Lucida Sans","LucidaSans-Demi","Lucida Sans Demibold Roman.ttf","*",0,0,0,"-","-"]
/*374*/,["T","T",50,10,"Lucida Sans","LucidaSans-DemiItalic","Lucida Sans Demibold Italic.ttf","*",0,0,0,"-","-"]
/*375*/,["T","N",50,10,"Lucida Sans Unicode","LucidaSansUnicode","Lucida Sans Unicode.ttf","*",0,0,0,"-","-"]
/*376*/,["T","N",51,10,"Microsoft Sans Serif","MicrosoftSansSerif","Microsoft Sans Serif (2).ttf","*",0,0,0,"-","-"]
/*377*/,["T","N",52,10,"Miriam","Miriam","Miriam.ttf","*",0,0,0,"-","-"]
/*378*/,["T","N",52,10,"Miriam Transparent","MiriamTransparent","Miriam Transparent.ttf","*",0,0,0,"-","-"]
/*379*/,["O","N",53,10,"Myriad Pro","MyriadPro-Regular","MyriadPro-Regular.otf","*",0,0,0,"-","-"]
/*380*/,["O","I",54,10,"Myriad Pro","MyriadPro-It","MyriadPro-It.otf","*",0,0,0,"-","-"]
/*381*/,["O","B",54,10,"Myriad Pro","MyriadPro-Bold","MyriadPro-Bold.otf","*",0,0,0,"-","-"]
/*382*/,["O","T",54,10,"Myriad Pro","MyriadPro-BoldIt","MyriadPro-BoldIt.otf","*",0,0,0,"-","-"]
/*383*/,["O","N",54,10,"Myriad Pro Black","MyriadPro-Black","MyriadPro-Black.otf","*",0,0,0,"-","-"]
/*384*/,["O","I",54,10,"Myriad Pro Black","MyriadPro-BlackIt","MyriadPro-BlackIt.otf","*",0,0,0,"-","-"]
/*385*/,["O","N",54,10,"Myriad Pro Black Cond","MyriadPro-BlackCond","MyriadPro-BlackCond.otf","*",0,0,0,"-","-"]
/*386*/,["O","I",54,10,"Myriad Pro Black Cond","MyriadPro-BlackCondIt","MyriadPro-BlackCondIt.otf","*",0,0,0,"-","-"]
/*387*/,["O","N",54,10,"Myriad Pro Cond","MyriadPro-Cond","MyriadPro-Cond.otf","*",0,0,0,"-","-"]
/*388*/,["O","I",54,10,"Myriad Pro Cond","MyriadPro-CondIt","MyriadPro-CondIt.otf","*",0,0,0,"-","-"]
/*389*/,["O","B",54,10,"Myriad Pro Cond","MyriadPro-BoldCond","MyriadPro-BoldCond.otf","*",0,0,0,"-","-"]
/*390*/,["O","T",54,10,"Myriad Pro Cond","MyriadPro-BoldCondIt","MyriadPro-BoldCondIt.otf","*",0,0,0,"-","-"]
/*391*/,["O","N",54,10,"Myriad Pro Light","MyriadPro-Light","MyriadPro-Light.otf","*",0,0,0,"-","-"]
/*392*/,["O","I",54,10,"Myriad Pro Light","MyriadPro-LightIt","MyriadPro-LightIt.otf","*",0,0,0,"-","-"]
/*393*/,["O","B",54,10,"Myriad Pro Light","MyriadPro-Semibold","MyriadPro-Semibold.otf","*",0,0,0,"-","-"]
/*394*/,["O","T",54,10,"Myriad Pro Light","MyriadPro-SemiboldIt","MyriadPro-SemiboldIt.otf","*",0,0,0,"-","-"]
/*395*/,["O","N",54,10,"Myriad Pro Light Cond","MyriadPro-LightCond","MyriadPro-LightCond.otf","*",0,0,0,"-","-"]
/*396*/,["O","I",54,10,"Myriad Pro Light Cond","MyriadPro-LightCondIt","MyriadPro-LightCondIt.otf","*",0,0,0,"-","-"]
/*397*/,["O","B",54,10,"Myriad Pro Light Cond","MyriadPro-SemiboldCond","MyriadPro-SemiboldCond.otf","*",0,0,0,"-","-"]
/*398*/,["O","T",54,10,"Myriad Pro Light Cond","MyriadPro-SemiboldCondIt","MyriadPro-SemiboldCondIt.otf","*",0,0,0,"-","-"]
/*399*/,["T","N",55,10,"Nokia Sans Wide","NokiaSansWide-Regular","Nokia Sans Wide Regular.ttf","*",0,0,0,"-","-"]
/*400*/,["T","I",55,10,"Nokia Sans Wide","NokiaSansWide-Italic","Nokia Sans Wide Italic.ttf","*",0,0,0,"-","-"]
/*401*/,["T","B",55,10,"Nokia Sans Wide","NokiaSansWide-Bold","Nokia Sans Wide Bold.ttf","*",0,0,0,"-","-"]
/*402*/,["T","T",55,10,"Nokia Sans Wide","NokiaSansWide-BoldItalic","Nokia Sans Wide Bold Italic.ttf","*",0,0,0,"-","-"]
/*403*/,["T","N",56,10,"Nokia Standard Multiscript","NokiaStandardMultiscript","Nokia Standard Multiscript.ttf","*",0,0,0,"-","-"]
/*404*/,["T","B",56,10,"Nokia Standard Multiscript","NokiaStandardMultiscript-Bold","Nokia Standard Multiscript Bold.ttf","*",0,0,0,"-","-"]
/*405*/,["T","N",32,10,"Nu World","NuWorld","Nu World.ttf","*",0,0,0,"-","-"]
/*406*/,["O","N",32,10,"Poplar Std","PoplarStd","PoplarStd.otf","*",0,0,0,"-","-"]
/*407*/,["T","N",57,10,"SAfon","SAMT","SAfon.ttf","*",0,0,0,"-","-"]
/*408*/,["T","B",57,10,"SAFon","SAFon-BoldMT","SAFon Bold.ttf","*",0,0,0,"-","-"]
/*409*/,["T","N",58,10,"Segoe UI","SegoeUI","Segoe UI.ttf","*",0,0,0,"-","-"]
/*410*/,["T","I",58,10,"Segoe UI","SegoeUI-Italic","Segoe UI Italic.ttf","*",0,0,0,"-","-"]
/*411*/,["T","B",58,10,"Segoe UI","SegoeUI-Bold","Segoe UI Bold.ttf","*",0,0,0,"-","-"]
/*412*/,["T","T",58,10,"Segoe UI","SegoeUI-BoldItalic","Segoe UI Bold Italic.ttf","*",0,0,0,"-","-"]
/*413*/,["T","N",59,10,"@SimHei","SimHei","SimHei.ttf","*",0,0,0,"-","-"]
/*414*/,["T","N",33,10,"Simplified Arabic","SimplifiedArabic","Simplified Arabic.ttf","*",0,0,0,"-","-"]
/*415*/,["T","B",33,10,"Simplified Arabic","SimplifiedArabic-Bold","Simplified Arabic Bold.ttf","*",0,0,0,"-","-"]
/*416*/,["T","N",60,10,"Tahoma","Tahoma","Tahoma.ttf","*",0,0,0,"-","-"]
/*417*/,["T","B",60,10,"Tahoma","Tahoma-Bold","Tahoma Bold.ttf","*",0,0,0,"-","-"]
/*418*/,["T","N",61,10,"Trebuchet MS","TrebuchetMS","Trebuchet MS.ttf","*",0,0,0,"-","-"]
/*419*/,["T","I",61,10,"Trebuchet MS","TrebuchetMS-Italic","Trebuchet MS Italic.ttf","*",0,0,0,"-","-"]
/*420*/,["T","B",61,10,"Trebuchet MS","TrebuchetMS-Bold","Trebuchet MS Bold.ttf","*",0,0,0,"-","-"]
/*421*/,["T","T",61,10,"Trebuchet MS","Trebuchet-BoldItalic","Trebuchet MS Bold Italic.ttf","*",0,0,0,"-","-"]
/*422*/,["T","N",62,10,"Verdana","Verdana","Verdana.ttf","*",0,0,0,"-","-"]
/*423*/,["T","I",62,10,"Verdana","Verdana-Italic","Verdana Italic.ttf","*",0,0,0,"-","-"]
/*424*/,["T","B",62,10,"Verdana","Verdana-Bold","Verdana Bold.ttf","*",0,0,0,"-","-"]
/*425*/,["T","T",62,10,"Verdana","Verdana-BoldItalic","Verdana Bold Italic.ttf","*",0,0,0,"-","-"]
/*426*/,["T","N",63,12,"a_AntiqueGr","AAntiqueGr","a_AntiqueGr.ttf","*",0,0,0,"-","-"]
/*427*/,["T","N",63,12,"a_AntiqueTitulGr","AAntiqueTitulGr","a_AntiqueTitulGr.ttf","*",0,0,0,"-","-"]
/*428*/,["T","N",63,12,"a_AntiqueTrady","AAntiqueTrady","a_AntiqueTrady.ttf","*",0,0,0,"-","-"]
/*429*/,["T","N",63,12,"a_AntiqueTradyNr","AAntiqueTradyNr","a_AntiqueTradyNr.ttf","*",0,0,0,"-","-"]
/*430*/,["T","N",64,12,"Academia","AcademiaRoma","Academia Roman.ttf","*",0,0,0,"-","-"]
/*431*/,["T","I",64,12,"Academia","AcademiaItali","Academia Italic.ttf","*",0,0,0,"-","-"]
/*432*/,["T","B",64,12,"Academia","AcademiaBol","Academia Bold.ttf","*",0,0,0,"-","-"]
/*433*/,["T","I",65,12,"Academy","Academy-Italic","Academy Italic.ttf","*",0,0,0,"-","-"]
/*434*/,["T","N",65,12,"Academy Ho","AcademyHo","Academy Ho.ttf","*",0,0,0,"-","-"]
/*435*/,["O","N",66,12,"Adobe Caslon Pro","ACaslonPro-Regular","ACaslonPro-Regular.otf","*",0,0,0,"-","-"]
/*436*/,["O","I",66,12,"Adobe Caslon Pro","ACaslonPro-Italic","ACaslonPro-Italic.otf","*",0,0,0,"-","-"]
/*437*/,["O","B",66,12,"Adobe Caslon Pro","ACaslonPro-Semibold","ACaslonPro-Semibold.otf","*",0,0,0,"-","-"]
/*438*/,["O","T",66,12,"Adobe Caslon Pro","ACaslonPro-SemiboldItalic","ACaslonPro-SemiboldItalic.otf","*",0,0,0,"-","-"]
/*439*/,["O","N",66,12,"Adobe Caslon Pro Bold","ACaslonPro-Bold","ACaslonPro-Bold.otf","*",0,0,0,"-","-"]
/*440*/,["O","I",66,12,"Adobe Caslon Pro Bold","ACaslonPro-BoldItalic","ACaslonPro-BoldItalic.otf","*",0,0,0,"-","-"]
/*441*/,["O","N",67,12,"Adobe Garamond Pro","AGaramondPro-Regular","AGaramondPro-Regular.otf","*",0,0,0,"-","-"]
/*442*/,["O","I",67,12,"Adobe Garamond Pro","AGaramondPro-Italic","AGaramondPro-Italic.otf","*",0,0,0,"-","-"]
/*443*/,["O","B",67,12,"Adobe Garamond Pro","AGaramondPro-Semibold","AGaramondPro-Semibold.otf","*",0,0,0,"-","-"]
/*444*/,["O","T",67,12,"Adobe Garamond Pro","AGaramondPro-SemiboldItalic","AGaramondPro-SemiboldItalic.otf","*",0,0,0,"-","-"]
/*445*/,["T","N",68,12,"Andalus","Andalus","Andalus.ttf","*",0,0,0,"-","-"]
/*446*/,["T","N",69,12,"Angsana New","AngsanaNew","Angsana New.ttf","*",0,0,0,"-","-"]
/*447*/,["T","I",69,12,"Angsana New","AngsanaNew-Italic","Angsana New Italic.ttf","*",0,0,0,"-","-"]
/*448*/,["T","B",69,12,"Angsana New","AngsanaNew-Bold","Angsana New Bold.ttf","*",0,0,0,"-","-"]
/*449*/,["T","T",69,12,"Angsana New","AngsanaNew-BoldItalic","Angsana New Bold Italic.ttf","*",0,0,0,"-","-"]
/*450*/,["T","N",69,12,"AngsanaUPC","AngsanaUPC","AngsanaUPC.ttf","*",0,0,0,"-","-"]
/*451*/,["T","I",69,12,"AngsanaUPC","AngsanaUPC-Italic","AngsanaUPC  Italic.ttf","*",0,0,0,"-","-"]
/*452*/,["T","B",69,12,"AngsanaUPC","AngsanaUPC-Bold","AngsanaUPC  Bold.ttf","*",0,0,0,"-","-"]
/*453*/,["T","T",69,12,"AngsanaUPC","AngsanaUPC-BoldItalic","AngsanaUPC  Bold Italic.ttf","*",0,0,0,"-","-"]
/*454*/,["T","N",70,12,"Bookman Old Style","BookmanOldStyle","Bookman Old Style.ttf","*",0,0,0,"-","-"]
/*455*/,["T","I",70,12,"Bookman Old Style","BookmanOldStyle-Italic","Bookman Old Style Italic.ttf","*",0,0,0,"-","-"]
/*456*/,["T","B",70,12,"Bookman Old Style","BookmanOldStyle-Bold","Bookman Old Style Bold.ttf","*",0,0,0,"-","-"]
/*457*/,["T","T",70,12,"Bookman Old Style","BookmanOldStyle-BoldItalic","Bookman Old Style Bold Italic.ttf","*",0,0,0,"-","-"]
/*458*/,["T","N",68,12,"cmmi10","Cmmi10","cmmi10.ttf","*",0,0,0,"-","-"]
/*459*/,["T","N",68,12,"cmr10","Cmr10","cmr10.ttf","*",0,0,0,"-","-"]
/*460*/,["T","N",71,12,"David","David-Reg","David.ttf","*",0,0,0,"-","-"]
/*461*/,["T","B",71,12,"David","David-Bold","David Bold.ttf","*",0,0,0,"-","-"]
/*462*/,["T","N",71,12,"David Transparent","DavidTransparent","David Transparent.ttf","*",0,0,0,"-","-"]
/*463*/,["T","N",72,12,"EucrosiaUPC","EucrosiaUPC","EucrosiaUPC.ttf","*",0,0,0,"-","-"]
/*464*/,["T","I",72,12,"EucrosiaUPC","EucrosiaUPCItalic","EucrosiaUPC Italic.ttf","*",0,0,0,"-","-"]
/*465*/,["T","B",72,12,"EucrosiaUPC","EucrosiaUPCBold","EucrosiaUPC Bold.ttf","*",0,0,0,"-","-"]
/*466*/,["T","T",72,12,"EucrosiaUPC","EucrosiaUPCBoldItalic","EucrosiaUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*467*/,["T","N",68,12,"FrankRuehl","FrankRuehl","FrankRuehl.ttf","*",0,0,0,"-","-"]
/*468*/,["T","N",73,12,"Garamond","Garamond","Garamond.ttf","*",0,0,0,"-","-"]
/*469*/,["T","I",73,12,"Garamond","Garamond-Italic","Garamond Italic.ttf","*",0,0,0,"-","-"]
/*470*/,["T","B",73,12,"Garamond","Garamond-Bold","Garamond Bold.ttf","*",0,0,0,"-","-"]
/*471*/,["T","N",74,12,"Georgia","Georgia","Georgia.ttf","*",0,0,0,"-","-"]
/*472*/,["T","I",74,12,"Georgia","Georgia-Italic","Georgia Italic.ttf","*",0,0,0,"-","-"]
/*473*/,["T","B",74,12,"Georgia","Georgia-Bold","Georgia Bold.ttf","*",0,0,0,"-","-"]
/*474*/,["T","T",74,12,"Georgia","Georgia-BoldItalic","Georgia Bold Italic.ttf","*",0,0,0,"-","-"]
/*475*/,["T","N",75,12,"KodchiangUPC","KodchiangUPC","KodchiangUPC.ttf","*",0,0,0,"-","-"]
/*476*/,["T","I",75,12,"KodchiangUPC","KodchiangUPC-Italic","KodchiangUPC Italic.ttf","*",0,0,0,"-","-"]
/*477*/,["T","B",75,12,"KodchiangUPC","KodchiangUPC-Bold","KodchiangUPC Bold.ttf","*",0,0,0,"-","-"]
/*478*/,["T","T",75,12,"KodchiangUPC","KodchiangUPC-BoldItalic","KodchiangUPC Bold Italic.ttf","*",0,0,0,"-","-"]
/*479*/,["O","N",76,12,"Minion Pro","MinionPro-Regular","MinionPro-Regular.otf","*",0,0,0,"-","-"]
/*480*/,["O","I",76,12,"Minion Pro","MinionPro-It","MinionPro-It.otf","*",0,0,0,"-","-"]
/*481*/,["O","B",76,12,"Minion Pro","MinionPro-Bold","MinionPro-Bold.otf","*",0,0,0,"-","-"]
/*482*/,["O","T",76,12,"Minion Pro","MinionPro-BoldIt","MinionPro-BoldIt.otf","*",0,0,0,"-","-"]
/*483*/,["O","N",76,12,"Minion Pro SmBd","MinionPro-Semibold","MinionPro-Semibold.otf","*",0,0,0,"-","-"]
/*484*/,["O","I",76,12,"Minion Pro SmBd","MinionPro-SemiboldIt","MinionPro-SemiboldIt.otf","*",0,0,0,"-","-"]
/*485*/,["T","N",77,12,"Palatino Linotype","PalatinoLinotype-Roman","Palatino Linotype.ttf","*",0,0,0,"-","-"]
/*486*/,["T","I",77,12,"Palatino Linotype","PalatinoLinotype-Italic","Palatino Linotype Italic.ttf","*",0,0,0,"-","-"]
/*487*/,["T","B",77,12,"Palatino Linotype","PalatinoLinotype-Bold","Palatino Linotype Bold.ttf","*",0,0,0,"-","-"]
/*488*/,["T","T",77,12,"Palatino Linotype","PalatinoLinotype-BoldItalic","Palatino Linotype Bold Italic.ttf","*",0,0,0,"-","-"]
/*489*/,["T","N",78,12,"PetersburgCTT","PetersburgCTT-Regular","PetersburgCTT.ttf","*",0,0,0,"-","-"]
/*490*/,["T","I",78,12,"PetersburgCTT","PetersburgCTT-Italic","PetersburgCTT Italic.ttf","*",0,0,0,"-","-"]
/*491*/,["T","N",23,12,"Sylfaen","Sylfaen","Sylfaen-.ttf","*",0,0,0,"-","-"]
/*492*/,["T","N",79,12,"Times New Roman","TimesNewRomanPSMT","Times New Roman.ttf","*",0,0,0,"-","-"]
/*493*/,["T","I",79,12,"Times New Roman","TimesNewRomanPS-ItalicMT","Times New Roman Italic.ttf","*",0,0,0,"-","-"]
/*494*/,["T","B",79,12,"Times New Roman","TimesNewRomanPS-BoldMT","Times New Roman Bold.ttf","*",0,0,0,"-","-"]
/*495*/,["T","T",79,12,"Times New Roman","TimesNewRomanPS-BoldItalicMT","Times New Roman Bold Italic.ttf","*",0,0,0,"-","-"]
/*496*/,["T","N",80,12,"Traditional Arabic","TraditionalArabic","Traditional Arabic.ttf","*",0,0,0,"-","-"]
/*497*/,["T","B",80,12,"Traditional Arabic","TraditionalArabic-Bold","Traditional Arabic Bold.ttf","*",0,0,0,"-","-"]
/*498*/,["O","N",81,12,"Trajan Pro","TrajanPro-Regular","TrajanPro-Regular.otf","*",0,0,0,"-","-"]
/*499*/,["O","B",81,12,"Trajan Pro","TrajanPro-Bold","TrajanPro-Bold.otf","*",0,0,0,"-","-"]
/*500*/,["T","N",82,13,"Arial Alternative Symbol","ArialAlternativeSymbol","Arial Alternative Symbol.ttf","*",0,0,0,"-","-"]
/*501*/,["T","N",82,13,"cmex10","Cmex10","cmex10.ttf","*",0,0,0,"-","-"]
/*502*/,["T","N",82,13,"cmsy10","Cmsy10","cmsy10.ttf","*",0,0,0,"-","-"]
/*503*/,["T","N",83,13,"Euclid","Euclid","Euclid.ttf","*",0,0,0,"-","-"]
/*504*/,["T","I",83,13,"Euclid","Euclid-Italic","Euclid Italic.ttf","*",0,0,0,"-","-"]
/*505*/,["T","B",83,13,"Euclid","Euclid-Bold","Euclid Bold.ttf","*",0,0,0,"-","-"]
/*506*/,["T","T",83,13,"Euclid","Euclid-BoldItalic","Euclid Bold Italic.ttf","*",0,0,0,"-","-"]
/*507*/,["T","N",83,13,"Euclid Extra","EuclidExtra","Euclid Extra.ttf","*",0,0,0,"-","-"]
/*508*/,["T","B",83,13,"Euclid Extra","EuclidExtra-Bold","Euclid Extra Bold.ttf","*",0,0,0,"-","-"]
/*509*/,["T","N",83,13,"Euclid Fraktur","EuclidFraktur","Euclid Fraktur.ttf","*",0,0,0,"-","-"]
/*510*/,["T","B",83,13,"Euclid Fraktur","EuclidFraktur-Bold","Euclid Fraktur Bold.ttf","*",0,0,0,"-","-"]
/*511*/,["T","N",83,13,"Euclid Math One","EuclidMathOne","Euclid Math One.ttf","*",0,0,0,"-","-"]
/*512*/,["T","B",83,13,"Euclid Math One","EuclidMathOne-Bold","Euclid Math One Bold.ttf","*",0,0,0,"-","-"]
/*513*/,["T","N",83,13,"Euclid Math Two","EuclidMathTwo","Euclid Math Two.ttf","*",0,0,0,"-","-"]
/*514*/,["T","B",83,13,"Euclid Math Two","EuclidMathTwo-Bold","Euclid Math Two Bold.ttf","*",0,0,0,"-","-"]
/*515*/,["T","N",83,13,"Euclid Symbol","EuclidSymbol","Euclid Symbol.ttf","*",0,0,0,"-","-"]
/*516*/,["T","I",83,13,"Euclid Symbol","EuclidSymbol-Italic","Euclid Symbol Italic.ttf","*",0,0,0,"-","-"]
/*517*/,["T","B",83,13,"Euclid Symbol","EuclidSymbol-Bold","Euclid Symbol Bold.ttf","*",0,0,0,"-","-"]
/*518*/,["T","T",83,13,"Euclid Symbol","EuclidSymbol-BoldItalic","Euclid Symbol Bold Italic.ttf","*",0,0,0,"-","-"]
/*519*/,["T","N",82,13,"Euro Sign","EuroSig","Euro Sign.ttf","*",0,0,0,"-","-"]
/*520*/,["T","N",83,13,"Fences","Fences Plain","Fences Plain.ttf","*",0,0,0,"-","-"]
/*521*/,["T","N",82,13,"Geotype TT","GeotypeTT","Geotype TT.ttf","*",0,0,0,"-","-"]
/*522*/,["T","N",84,13,"Mathematica1","Mathematica1","Mathematica1.ttf","*",0,0,0,"-","-"]
/*523*/,["T","B",84,13,"Mathematica1","Mathematica1-Bold","Mathematica1-Bold.ttf","*",0,0,0,"-","-"]
/*524*/,["T","N",84,13,"Mathematica1Mono","Mathematica1Mono","Mathematica1Mono.ttf","*",0,0,0,"-","-"]
/*525*/,["T","B",84,13,"Mathematica1Mono","Mathematica1Mono-Bold","Mathematica1Mono-Bold.ttf","*",0,0,0,"-","-"]
/*526*/,["T","N",84,13,"Mathematica2","Mathematica2","Mathematica2.ttf","*",0,0,0,"-","-"]
/*527*/,["T","B",84,13,"Mathematica2","Mathematica2-Bold","Mathematica2-Bold.ttf","*",0,0,0,"-","-"]
/*528*/,["T","N",84,13,"Mathematica2Mono","Mathematica2Mono","Mathematica2Mono.ttf","*",0,0,0,"-","-"]
/*529*/,["T","B",84,13,"Mathematica2Mono","Mathematica2Mono-Bold","Mathematica2Mono-Bold.ttf","*",0,0,0,"-","-"]
/*530*/,["T","N",84,13,"Mathematica3","Mathematica3","Mathematica3.ttf","*",0,0,0,"-","-"]
/*531*/,["T","B",84,13,"Mathematica3","Mathematica3-Bold","Mathematica3-Bold.ttf","*",0,0,0,"-","-"]
/*532*/,["T","N",84,13,"Mathematica3Mono","Mathematica3Mono","Mathematica3Mono.ttf","*",0,0,0,"-","-"]
/*533*/,["T","B",84,13,"Mathematica3Mono","Mathematica3Mono-Bold","Mathematica3Mono-Bold.ttf","*",0,0,0,"-","-"]
/*534*/,["T","N",84,13,"Mathematica4","Mathematica4","Mathematica4.ttf","*",0,0,0,"-","-"]
/*535*/,["T","B",84,13,"Mathematica4","Mathematica4-Bold","Mathematica4-Bold.ttf","*",0,0,0,"-","-"]
/*536*/,["T","N",84,13,"Mathematica4Mono","Mathematica4Mono","Mathematica4Mono.ttf","*",0,0,0,"-","-"]
/*537*/,["T","B",84,13,"Mathematica4Mono","Mathematica4Mono-Bold","Mathematica4Mono-Bold.ttf","*",0,0,0,"-","-"]
/*538*/,["T","N",84,13,"Mathematica5","Mathematica5","Mathematica5.ttf","*",0,0,0,"-","-"]
/*539*/,["T","B",84,13,"Mathematica5","Mathematica5Bold","Mathematica5-Bold.ttf","*",0,0,0,"-","-"]
/*540*/,["T","N",84,13,"Mathematica5Mono","Mathematica5Mono","Mathematica5Mono.ttf","*",0,0,0,"-","-"]
/*541*/,["T","B",84,13,"Mathematica5Mono","Mathematica5MonoBold","Mathematica5Mono Bold.ttf","*",0,0,0,"-","-"]
/*542*/,["T","N",84,13,"Mathematica6","Mathematica6Bold","Mathematica6 Bold.ttf","*",0,0,0,"-","-"]
/*543*/,["T","N",84,13,"Mathematica6Mono","Mathematica6MonoBold","Mathematica6Mono Bold.ttf","*",0,0,0,"-","-"]
/*544*/,["T","N",84,13,"Mathematica7","Mathematica7Bold","Mathematica7 Bold.ttf","*",0,0,0,"-","-"]
/*545*/,["T","N",84,13,"Mathematica7Mono","Mathematica7MonoBold","Mathematica7Mono Bold.ttf","*",0,0,0,"-","-"]
/*546*/,["T","N",82,13,"Monotype Sorts","MonotypeSorts","Monotype Sorts.ttf","*",0,0,0,"-","-"]
/*547*/,["T","N",82,13,"MS Outlook","MS-Outlook","MS Outlook.ttf","*",0,0,0,"-","-"]
/*548*/,["T","N",83,13,"MT Extra","MT-Extra","MT Extra.ttf","*",0,0,0,"-","-"]
/*549*/,["T","N",82,13,"SLGreek","PS=SLGreek","SLGreek.ttf","*",0,0,0,"-","-"]
/*550*/,["T","N",82,13,"Symbol","SymbolMT","Symbol+.ttf","*",0,0,0,"-","-"]
/*551*/,["T","N",82,13,"Webdings","Webdings","Webdings.ttf","*",0,0,0,"-","-"]
/*552*/,["T","N",82,13,"Wingdings","Wingdings-Regular","Wingdings.ttf","*",0,0,0,"-","-"]
/*553*/,["O","N",85,14,"Adobe Thai","AdobeThai-Regular","AdobeThai-Regular.otf","*",0,0,0,"-","-"]
/*554*/,["O","I",85,14,"Adobe Thai","AdobeThai-Italic","AdobeThai-Italic.otf","*",0,0,0,"-","-"]
/*555*/,["O","B",85,14,"Adobe Thai","AdobeThai-Bold","AdobeThai-Bold.otf","*",0,0,0,"-","-"]
/*556*/,["O","T",85,14,"Adobe Thai","AdobeThai-BoldItalic","AdobeThai-BoldItalic.otf","*",0,0,0,"-","-"]
/*557*/,["T","N",85,14,"@GulimChe","GulimChe","GulimChe.ttf","*",0,0,0,"-","-"]
/*558*/,["T","N",85,14,"MingLiU","MingLiU","MingLiU.ttf","*",0,0,0,"-","-"]
/*559*/,["T","N",85,14,"@MS Gothic","MS-Gothic","MS Gothic.ttf","*",0,0,0,"-","-"]
/*560*/,["T","N",85,14,"MS Hei","MS Hei","MS Hei.ttf","*",0,0,0,"-","-"]
/*561*/,["T","N",85,14,"MS Song","MS Song","MS Song.ttf","*",0,0,0,"-","-"]
/*562*/,["T","N",85,14,"SLHebrew","SLHebrew","SLHebrew.ttf","*",0,0,0,"-","-"]
/*563*/,["T","N",86,15,"Consolas","Consolas","Consolas.ttf","*",0,0,0,"-","-"]
/*564*/,["T","I",86,15,"Consolas","Consolas-Italic","Consolas Italic.ttf","*",0,0,0,"-","-"]
/*565*/,["T","B",86,15,"Consolas","Consolas-Bold","Consolas Bold.ttf","*",0,0,0,"-","-"]
/*566*/,["T","T",86,15,"Consolas","Consolas-BoldItalic","Consolas Bold Italic.ttf","*",0,0,0,"-","-"]
/*567*/,["T","N",23,15,"Fixed Miriam Transparent","FixedMiriamTransparent","miriam fixed transp.ttf","*",0,0,0,"-","-"]
/*568*/,["O","N",86,15,"Letter Gothic Std","LetterGothicStd","LetterGothicStd.otf","*",0,0,0,"-","-"]
/*569*/,["O","I",86,15,"Letter Gothic Std","LetterGothicStd-Slanted","LetterGothicStd-Slanted.otf","*",0,0,0,"-","-"]
/*570*/,["O","B",86,15,"Letter Gothic Std","LetterGothicStd-Bold","LetterGothicStd-Bold.otf","*",0,0,0,"-","-"]
/*571*/,["O","T",86,15,"Letter Gothic Std","LetterGothicStd-BoldSlanted","LetterGothicStd-BoldSlanted.otf","*",0,0,0,"-","-"]
/*572*/,["T","N",86,15,"Lucida Console","LucidaConsole","Lucida Console.ttf","*",0,0,0,"-","-"]
/*573*/,["T","N",86,15,"Simplified Arabic Fixed","SimplifiedArabicFixed","Simplified Arabic Fixed.ttf","*",0,0,0,"-","-"]
]
Set=[// #[TT,PS,Set]
/*0*/ [0,2,"+atm-mmm"]
/*1*/,[0,1,"+atm-sys"]
/*2*/,[43,0,"bible.sla-gre-heb"]
/*3*/,[67,0,"decor-caligr"]
/*4*/,[38,1,"decor-freehand"]
/*5*/,[11,0,"decor-gothic"]
/*6*/,[48,0,"decor-min"]
/*7*/,[45,0,"decor-more"]
/*8*/,[14,4,"serif-courier"]
/*9*/,[16,5,"serif-hidn"]
/*10*/,[97,34,"serif-not"]
/*11*/,[0,0,"serif-oval"]
/*12*/,[56,18,"serif-sharp"]
/*13*/,[53,0,"symbol"]
/*14*/,[6,4,"~asian"]
/*15*/,[7,4,"~console-monosp"]
]
Pth=[// #[files,Path]
/*0*/ [0,"C:/fnt/+atm-mmm/"]
/*1*/,[0,"C:/fnt/+atm-sys/"]
/*2*/,[0,"C:/fnt/bible.sla-gre-heb/"]
/*3*/,[0,"C:/fnt/bible.sla-gre-heb/orthodox.ucs8/"]
/*4*/,[0,"C:/fnt/decor-caligr/"]
/*5*/,[0,"C:/fnt/decor-caligr/Bickham/"]
/*6*/,[0,"C:/fnt/decor-caligr/Decor/"]
/*7*/,[0,"C:/fnt/decor-caligr/Esenin/"]
/*8*/,[0,"C:/fnt/decor-freehand/"]
/*9*/,[0,"C:/fnt/decor-freehand/BetinaScript/"]
/*10*/,[0,"C:/fnt/decor-freehand/Comic Sans/"]
/*11*/,[0,"C:/fnt/decor-freehand/Segoe/"]
/*12*/,[0,"C:/fnt/decor-gothic/"]
/*13*/,[0,"C:/fnt/decor-min/"]
/*14*/,[0,"C:/fnt/decor-min/Algerius/"]
/*15*/,[0,"C:/fnt/decor-min/Digital/"]
/*16*/,[0,"C:/fnt/decor-min/dots/"]
/*17*/,[0,"C:/fnt/decor-more/"]
/*18*/,[0,"C:/fnt/decor-more/art-nouveau/"]
/*19*/,[0,"C:/fnt/serif-courier/Courier New/"]
/*20*/,[0,"C:/fnt/serif-courier/Courier Std/"]
/*21*/,[0,"C:/fnt/serif-courier/Dillenia/"]
/*22*/,[0,"C:/fnt/serif-courier/ezra/"]
/*23*/,[0,"C:/fnt/serif-courier/"]
/*24*/,[0,"C:/fnt/serif-hidn/Albionic/"]
/*25*/,[0,"C:/fnt/serif-hidn/"]
/*26*/,[0,"C:/fnt/serif-hidn/iris/"]
/*27*/,[0,"C:/fnt/serif-hidn/Jasmine/"]
/*28*/,[0,"C:/fnt/serif-hidn/LithosPro/"]
/*29*/,[0,"C:/fnt/serif-not/Alterna/"]
/*30*/,[0,"C:/fnt/serif-not/JensonPro/"]
/*31*/,[0,"C:/fnt/serif-not/Aharoni/"]
/*32*/,[0,"C:/fnt/serif-not/"]
/*33*/,[0,"C:/fnt/serif-not/Arabic/"]
/*34*/,[0,"C:/fnt/serif-not/Arial 2008/"]
/*35*/,[0,"C:/fnt/serif-not/Arial Alternative/"]
/*36*/,[0,"C:/fnt/serif-not/Arial Narrow/"]
/*37*/,[0,"C:/fnt/serif-not/BellGothicStd/"]
/*38*/,[0,"C:/fnt/serif-not/Browallia/"]
/*39*/,[0,"C:/fnt/serif-not/calibri/"]
/*40*/,[0,"C:/fnt/serif-not/Cordia/"]
/*41*/,[0,"C:/fnt/serif-not/EpsySans/"]
/*42*/,[0,"C:/fnt/serif-not/Franklin Gothic Medium/"]
/*43*/,[0,"C:/fnt/serif-not/Freesia/"]
/*44*/,[0,"C:/fnt/serif-not/GillSans/"]
/*45*/,[0,"C:/fnt/serif-not/Impact/"]
/*46*/,[0,"C:/fnt/serif-not/HSgrotesk/"]
/*47*/,[0,"C:/fnt/serif-not/Iskar/"]
/*48*/,[0,"C:/fnt/serif-not/Levenim MT/"]
/*49*/,[0,"C:/fnt/serif-not/LilyUPC/"]
/*50*/,[0,"C:/fnt/serif-not/LucidaSans/"]
/*51*/,[0,"C:/fnt/serif-not/Ms Sans Serif/"]
/*52*/,[0,"C:/fnt/serif-not/Miriam/"]
/*53*/,[0,"C:/WINDOWS/Fonts/"]
/*54*/,[0,"C:/fnt/serif-not/MyriadPro/"]
/*55*/,[0,"C:/fnt/serif-not/Nokia Sans Wide/"]
/*56*/,[0,"C:/fnt/serif-not/Nokia Standard Multi/"]
/*57*/,[0,"C:/fnt/serif-not/SAfon/"]
/*58*/,[0,"C:/fnt/serif-not/SegoeUI/"]
/*59*/,[0,"C:/fnt/serif-not/SimHei/"]
/*60*/,[0,"C:/fnt/serif-not/Tahoma/"]
/*61*/,[0,"C:/fnt/serif-not/Trebuchet MS/"]
/*62*/,[0,"C:/fnt/serif-not/verdana/"]
/*63*/,[0,"C:/fnt/serif-sharp/Antique/"]
/*64*/,[0,"C:/fnt/serif-sharp/Academia/"]
/*65*/,[0,"C:/fnt/serif-sharp/Academy/"]
/*66*/,[0,"C:/fnt/serif-sharp/CaslonPro/"]
/*67*/,[0,"C:/fnt/serif-sharp/GaramondPro/"]
/*68*/,[0,"C:/fnt/serif-sharp/"]
/*69*/,[0,"C:/fnt/serif-sharp/Angsana/"]
/*70*/,[0,"C:/fnt/serif-sharp/Bookman Old Style/"]
/*71*/,[0,"C:/fnt/serif-sharp/David/"]
/*72*/,[0,"C:/fnt/serif-sharp/Eucrosia/"]
/*73*/,[0,"C:/fnt/serif-sharp/Garamond/"]
/*74*/,[0,"C:/fnt/serif-sharp/Georgia/"]
/*75*/,[0,"C:/fnt/serif-sharp/Kodchiang/"]
/*76*/,[0,"C:/fnt/serif-sharp/MinionPro/"]
/*77*/,[0,"C:/fnt/serif-sharp/Palatino/"]
/*78*/,[0,"C:/fnt/serif-sharp/Petersburg/"]
/*79*/,[0,"C:/fnt/serif-sharp/Times New Roman/"]
/*80*/,[0,"C:/fnt/serif-sharp/Arabic/"]
/*81*/,[0,"C:/fnt/serif-sharp/Trajan/"]
/*82*/,[0,"C:/fnt/symbol/"]
/*83*/,[0,"C:/fnt/symbol/Math-euclid/"]
/*84*/,[0,"C:/fnt/symbol/math/"]
/*85*/,[0,"C:/fnt/~asian/"]
/*86*/,[0,"C:/fnt/~console-monosp/"]
]
Win_Mac="W"; catalog="ea-2010";
loadstatus='data loaded';outlog_('<<<');a2def();//alert('>>>ea-2010.js<<<')
// Generated by FontOrg.js (3.1a 2010.Nov) 
